jsdom/jsdom

- lib/jsdom/browser/Window.js
- lib/jsdom/browser/documentAdapter.js
Fixes issue #1010, by removing the BOMS.
> remove byte-order-marks

- lib/jsdom/living/node.js
- test/living-dom/node-contains.js
Caused by d7790e7c118377085b041f73e2046ec768496680
> Node.prototype.contains should return a boolean, not a number

- lib/jsdom/events/EventTarget.js
- package.json
- test/living-dom/event-target.js
- test/runner
- test/w3c/index.js
- test/w3c/w3ctest.js
- test/worker-runner.js
Please help @Sebmaster! It looks like the first 9 w3c tests pass and the last 9 do not? I tried rearranging them and the same thing happens. My best guess is something wrong with w3ctest.js?
> Upgrading NodeUnit reveals failures in w3c tests?

- lib/jsdom/level2/html.js
- test/jsdom/env.js
- test/jsdom/index.js
js resources are mostly served compressed from cdns eg. http://sd1.gemvara.net/static/bundle-bundle_site_head_39e0ef67d1c.js
> 1. Handling compression, 2. Using charset from headers

- .gitmodules
Everything keeps breaking when I do. Very frustrating.
Sometimes I can get web-platform-tests itself updated, but the tools subsubmodule is not correct when I do.
Other times when I try to do things recursively I get a bunch of errors about tools not being a Git repository.
> I can't figure out how to update our web-platform-tests submodules

- lib/jsdom/browser/htmltodom.js
- lib/jsdom/level1/core.js
- lib/jsdom/level2/core.js
- lib/jsdom/living/document.js
- lib/jsdom/living/helpers/shared-symbols.js
- lib/jsdom/living/node.js
- test/level1/core.js
- test/level1/html.js
- test/level2/core.js
- test/living-dom/node-clone-node.js
- test/runner
- test/worker-runner.js
Review appreciated. Started out with fixing #1142 but as usual I got carried away.
> Rewrite cloning, plus some other fixes

- lib/jsdom/level2/html.js
- test/living-html/htmlbuttonelement.js
- test/runner
- test/worker-runner.js
Subsumes and builds on #1088. PTAL @Joris-van-der-Wel or @Sebmaster.
> Make clicking buttons dispatch submit; fix button type

- package.json
gah, url()'s with quotes in them just never worked, sorry. I fixed it and added a test.
> cssstyle 0.2.29 fixed url parsing with quotes, fixes #1160

- lib/jsdom/vm-shim.js
- test/jsdom/inside-worker-smoke-tests.js
Fixes #1175 
Review please @Sebmaster? :)
> Update browser vm shim to copy global built-ins to the sandbox

- lib/jsdom/browser/history.js
- lib/jsdom/browser/location.js
- lib/jsdom/level2/events.js
- lib/jsdom/living/hash-change-event.js
- package.json
A jsdom/env test is failing currently due to https://github.com/jsdom/whatwg-url/issues/31
> Update Location to use whatwg-url's URLUtils

- lib/jsdom/level2/html.js
- lib/jsdom/living/node-iterator.js
- test/w3c/index.js
Blocked on https://github.com/w3c/web-platform-tests/pull/2107
> Update web platform tests and add a bunch of HTML element stubs

- README.md
- lib/jsdom.js
- lib/jsdom/browser/htmltodom.js
- lib/jsdom/living/helpers/internal-constants.js
- test/jsdom/node-location.js
- test/runner
- test/worker-runner.js
Fixes #1194, pending further parse5 updates to make it even better: https://github.com/inikulin/parse5/issues/67
/cc @bterlson. Should meet your needs for now.
> Add jsdom.nodeLocation

- README.md
- lib/jsdom.js
- package.json
- test/browser-runner.js
- test/jsdom/reconfigure-window.js
- test/runner
- test/worker-runner.js
@cpojer, does this look like it will meet your needs?
> Add jsdom.reconfigureWindow to solve #1208

- .travis.yml
In case on of those fails the other one will still be executed
> Split travis testing up into 2 commands

- lib/jsdom/level1/core.js
- lib/jsdom/level2/html.js
- test/web-platform-tests/index.js
Hope I did the to-upstream thing correctly. PR to wpt is at https://github.com/w3c/web-platform-tests/pull/2381.
> Fix writeln to handle multiple arguments correctly

- .travis.yml
Not very DRY, but for now we'll live.
Doing a PR to test that this actually fixes things.
> Fix #1329: canvas tests Travis config

- lib/jsdom/living/nodes/HTMLCanvasElement-impl.js
This should finally fix master after #1333.
> Properly catch out-of-bounds args in <canvas>#width/height

- Contributing.md
Good for inattentive people like me who missed the links above this.
> Clarify process for running tests, and fix a spelling error

- lib/jsdom/living/events/EventTarget-impl.js
- test/web-platform-tests/to-upstream/dom/events/EventTarget-this-of-listener.html
Just doing a PR to get CI coverage since my internet connection is not good enough to run WPT locally.
> Fix #1369: this inside event listeners was wrong

- package.json
- test/level2/style.js
Test does not yet pass (so we can't merge this PR yet) due to https://github.com/chad3814/CSSStyleDeclaration/issues/37
> Upgrade cssstyle and add test showing it fixes #1353

- lib/jsdom/living/nodes/HTMLOptionElement-impl.js
- test/web-platform-tests/to-upstream.js
- test/web-platform-tests/to-upstream/html/semantics/forms/the-select-element/select-multiple.html
See https://github.com/facebook/react/pull/6620 and more specifically this test: https://github.com/facebook/react/pull/6620/files#diff-b9c54bc7179ecdb2e1520a1f1d87d3e5L241 that fails with jsdom 8.
> Multiple default values broken between jsdom 7 and 8.

- lib/jsdom/living/html-collection.js
- test/web-platform-tests/to-upstream.js
- test/web-platform-tests/to-upstream/dom/collections/HTMLCollection-iterator.html
> Implement HTMLCollection @@iterator

- lib/jsdom/living/helpers/focusing.js
- lib/jsdom/living/nodes/Document-impl.js
- lib/jsdom/living/nodes/Document.idl
- lib/jsdom/living/nodes/HTMLElement-impl.js
- test/web-platform-tests/index.js
> Browsing context container focus behavior

- AUTHORS.txt
- lib/jsdom/living/nodes/Text-impl.js
- lib/jsdom/living/nodes/Text.idl
- test/web-platform-tests/to-upstream.js
- test/web-platform-tests/to-upstream/dom/nodes/Text-wholeText.html
> add wholeText property

- package.json
- test/web-platform-tests/to-upstream.js
- test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-escapes.html
Closes #1550. Drawn from https://github.com/tmpvar/jsdom/issues/1550#issuecomment-232588346.
Do not merge until nwmatcher 1.3.9 has been published, and at that point bump the package.json version required.
> Add more selector tests

- lib/jsdom/living/helpers/traversal.js
- lib/jsdom/living/html-collection.js
- lib/jsdom/living/nodes/Document-impl.js
- lib/jsdom/living/nodes/Document.idl
- test/level2/html.js
- test/web-platform-tests/index.js
Want to get a CI run in as locally I'm getting some strange test failures
> Various fixes to document accessors

- README.md
per https://github.com/tmpvar/jsdom/issues/885#issuecomment-230127793
> README, change xml link to the `x(ht)ml` tag

- lib/jsdom/living/nodes/HTMLHyperlinkElementUtils-impl.js
- test/web-platform-tests/index.js
Fixes the issue that changing the pathname of an HTMLAnchorElement
didn't update the href.
> Fix HTMLHyperlinkElementUtils pathname setter to update the href

- .eslintrc.json
- README.md
- lib/jsdom/browser/Window.js
- lib/jsdom/browser/htmltodom.js
- lib/jsdom/living/attributes.js
- lib/jsdom/living/events/Event-impl.js
- lib/jsdom/living/html-collection.js
- lib/jsdom/living/node-list.js
- lib/jsdom/living/nodes/Document-impl.js
- lib/jsdom/living/nodes/HTMLTableElement-impl.js
- lib/jsdom/virtual-console.js
- test/to-port-to-wpts/files/current-script.js
- test/to-port-to-wpts/history.js
- test/web-platform-tests/create-jsdom.js
Now that we are requiring Node v6, we can use these.
Making sure CI passes, then will merge.
> Use more modern JS features

- lib/jsdom/living/xmlhttprequest.js
> pre-allocate buffer in xmlhttprequest.js

- lib/jsdom/living/nodes/HTMLSelectElement-impl.js
- lib/jsdom/living/nodes/HTMLSelectElement.idl
- package.json
- test/web-platform-tests/to-upstream.js
- test/web-platform-tests/to-upstream/html/semantics/forms/the-select-element/select-selectedOptions.html
Implements: https://html.spec.whatwg.org/multipage/forms.html#dom-select-selectedoptions
Includes a to-upstream test as one did not exist in the testsuite.
> Implement HTMLSelectElement.selectedOptions

- lib/jsdom/living/xhr/FormData-impl.js
- lib/jsdom/living/xhr/FormData.idl
- test/web-platform-tests/index.js
Now that this is supported in webidl2js, we can use it here. Closes #1671.
/cc @TimothyGu \o/
> Enable FormData being iterable

- lib/jsdom/browser/Window.js
- lib/jsdom/living/dom-token-list.js
- lib/jsdom/living/events/EventTarget-impl.js
- lib/jsdom/living/file-api/Blob-impl.js
- lib/jsdom/living/file-api/FileReader-impl.js
- lib/jsdom/living/helpers/runtime-script-errors.js
- lib/jsdom/living/html-collection.js
- lib/jsdom/living/node-iterator.js
- lib/jsdom/living/node-list.js
- lib/jsdom/living/nodes/Document-impl.js
- lib/jsdom/living/nodes/Element-impl.js
- lib/jsdom/living/nodes/Node-impl.js
- lib/jsdom/living/nodes/ParentNode-impl.js
- lib/jsdom/living/xhr/FormData-impl.js
- lib/jsdom/living/xhr/FormData.idl
- lib/jsdom/living/xmlhttprequest-event-target.js
- lib/jsdom/living/xmlhttprequest-upload.js
- lib/jsdom/living/xmlhttprequest.js
- package.json
- test/web-platform-tests/to-upstream.js
This also fixes the behavior of setting document.body to null: it should throw a DOMException, not a TypeError.
Circularly depends on https://github.com/jsdom/webidl2js/pull/33.
> Upgrade to latest webidl2js features

- lib/api.js
- lib/jsdom/browser/Window.js
- lib/jsdom/browser/htmltodom.js
- lib/jsdom/living/domparsing/DOMParser-impl.js
- lib/jsdom/living/nodes/Document-impl.js
- lib/jsdom/living/nodes/Element-impl.js
- lib/jsdom/living/xmlhttprequest.js
- lib/old-api.js
They have never been fully supported or tested properly, and are a maintenance burden.
Closes #180. Closes #370.
> Remove support for custom parsers

- benchmark/document-suite.js
- benchmark/dom/construction.js
TODO: Figure out why the benchmark runner had no output before this fix. It should at least log some kind of error
> Fix benchmarks

- lib/jsdom/living/xmlhttprequest.js
This should improve correctness slightly, but it was mainly motivated by trying to fix a bug that in the end was not related to this code. Even though it did not fix the bug I was chasing, it was a good refactoring, so I thought I'd best commit it anyway.
> Refactor XHR's send() implementation

- lib/jsdom/browser/Window.js
- test/api/from-outside.js
Fix for [#1893](https://github.com/tmpvar/jsdom/issues/1893)
> Don't add timer if 'this' or 'this._document' are undefined or null

- lib/jsdom/browser/Window.js
- lib/jsdom/living/events/Event-impl.js
- lib/jsdom/living/nodes/Document-impl.js
- lib/jsdom/living/window/History-impl.js
- lib/jsdom/living/window/SessionHistory.js
- lib/jsdom/living/window/navigation.js
- test/web-platform-tests/index.js
- test/web-platform-tests/to-upstream.js
- test/web-platform-tests/to-upstream/html/browsers/browsing-the-web/navigating-across-documents/fragment-replace.html
This is a fairly minimal session history implementation.  Next Step is
to add some ability for SessionHistory to report when the `window`
object has changed.
> Define a session-history class

- lib/jsdom/browser/Window.js
- lib/jsdom/living/named-properties-window.js
- lib/jsdom/named-properties-tracker.js
- test/old-api/named-properties-tracker.js
- test/web-platform-tests/to-upstream/html/named-access-on-window/existing-prop.html
> Only track properties if it's undefined in proxy

- lib/jsdom/living/nodes/Document-impl.js
- test/web-platform-tests/index.js
> Return NodeList from document.getElementsByName()

- test/karma-webworker.conf.js
- test/karma.conf.js
> Fix browser testing

- test/api/options-run-scripts.js
> Skip stack trace line number test in browsers

- .mailmap
- AUTHORS.txt
In this way my past contribution is mapped correctly.
> Add my new name to .mailmap, update AUTHORS.txt

- test/api/options.js
> Test that we are not mutating the passed-in options object

- lib/jsdom/living/nodes/HTMLInputElement-impl.js
- test/web-platform-tests/to-upstream/html/semantics/forms/the-input-element/radio-click-events.html
> Emitting change and input events on radio input click

- lib/jsdom/browser/Window.js
- lib/jsdom/living/aborting/AbortController-impl.js
- lib/jsdom/living/aborting/AbortController.webidl
- lib/jsdom/living/aborting/AbortSignal-impl.js
- lib/jsdom/living/aborting/AbortSignal.webidl
- scripts/webidl/convert.js
- test/web-platform-tests/to-run.yaml
I'm really glad now we have Webidl2JSFactory.
> Implement AbortSignal

- lib/jsdom/utils.js
- test/web-platform-tests/to-run.yaml
A test for this was added in https://github.com/w3c/web-platform-tests/pull/8109.
> Don't include fragment in data: URL body

- lib/jsdom/living/nodes/ChildNode.webidl
- lib/jsdom/living/nodes/Element.webidl
- lib/jsdom/living/nodes/HTMLInputElement-impl.js
- lib/jsdom/living/nodes/HTMLInputElement.webidl
- lib/jsdom/living/nodes/HTMLMediaElement.webidl
- lib/jsdom/living/nodes/HTMLTextAreaElement-impl.js
- lib/jsdom/living/nodes/ParentNode.webidl
- lib/jsdom/living/xhr/FormData-impl.js
- lib/jsdom/living/xhr/FormData.webidl
- package.json
- Overloads
- Enumerations
- Update some IDL fragments from specs
Needs https://github.com/jsdom/webidl2js/pull/86
> Update to new webidl2js

- lib/jsdom/living/nodes/HTMLMeterElement-impl.js
- lib/jsdom/living/nodes/HTMLMeterElement.webidl
- test/web-platform-tests/to-run.yaml
> Implement more parts of <meter>

- lib/jsdom/living/websockets/WebSocket-impl-browser.js
- lib/jsdom/living/websockets/WebSocket-impl.js
- package.json
- test/web-platform-tests/to-run.yaml
- test/web-platform-tests/to-upstream/hr-time/performance-tojson-dont-upstream.html
> Make WebSocket compatible with browsers

- README.md
…as suggested by @domenic on the mailing list, https://groups.google.com/d/msg/jsdom/5bZXCNvqZmM/SBkb37V9AAAJ
Let me know if you want it placed somewhere else and/or want it rephrased.
> Add README entry about jsdom-devtools-formatter

- test/web-platform-tests/to-run.yaml
We're passing most tests in these directories.
> Enable more WPTs from html/semantics/

- package.json
- yarn.lock
Fixes https://github.com/jsdom/jsdom/issues/2260 and https://github.com/jsdom/jsdom/issues/2262.
> Upgrade NWSAPI to 2.0.3

- README.md
- lib/jsdom/browser/resources/per-document-resource-loader.js
- test/api/resources.js
> Add html element to `options` for custom resource loader

- lib/api.js
This was missed in f865e45fdbdf12d6a6874f69ea5cc80b39f9d575.
> Remove dead code

- test/web-platform-tests/run-wpts.js
- test/web-platform-tests/to-run.yaml
- test/web-platform-tests/wpt-manifest-utils.js
Also adds `[expected fail]` to the output as suggested in https://github.com/jsdom/jsdom/pull/2340#issuecomment-416244726.
> Roll Web Platform Tests

- lib/jsdom/living/events/Event-impl.js
- lib/jsdom/living/events/EventTarget-impl.js
- lib/jsdom/living/events/EventTarget.webidl
- test/web-platform-tests/to-run.yaml
Resolves https://github.com/jsdom/jsdom/issues/1609.
> Implement the `passive` option for event listeners

- .travis.yml
- README.md
- lib/jsdom/living/nodes/HTMLCanvasElement-impl.js
- lib/jsdom/living/nodes/HTMLImageElement-impl.js
- lib/jsdom/utils.js
Fixes Automattic/node-canvas#978
I'm not sure if there's a good way to add tests for this; would have to test against two different versions of node-canvas somehow.
> Support Canvas 2.x

- lib/jsdom/living/nodes/HTMLInputElement-impl.js
- test/web-platform-tests/to-run.yaml
This follows a spec update which was discussed in https://github.com/whatwg/html/issues/1666.
> Match names in radio button groups case-sensitively

- lib/jsdom/utils.js
> Don't attempt to load canvas-prebuilt

- lib/jsdom/living/helpers/focusing.js
- test/web-platform-tests/to-run.yaml
Per spec, in fire a focus event: https://html.spec.whatwg.org/multipage/interaction.html#fire-a-focus-event
> Set the composed flag for FocusEvent

- lib/jsdom/living/events/EventTarget-impl.js
- lib/jsdom/living/nodes/HTMLButtonElement-impl.js
- lib/jsdom/living/nodes/HTMLElement-impl.js
- lib/jsdom/living/nodes/HTMLInputElement-impl.js
- lib/jsdom/living/nodes/HTMLLabelElement-impl.js
- test/to-port-to-wpts/level2/html.js
- test/web-platform-tests/to-run.yaml
This adds steps regarding activation behavior from the [Dispatch an event](https://dom.spec.whatwg.org/#concept-event-dispatch) algorithm, replacing older code where the activation didn't bubble correctly.
I've also renamed the existing hooks to match the names used in the specification.
This fixes #2449 and #2367.
> Run activation behavior hooks from the event dispatch algorithm 

- lib/jsdom/living/nodes/HTMLElement-impl.js
- test/web-platform-tests/to-run.yaml
Spec: https://html.spec.whatwg.org/multipage/interactive-elements.html#the-summary-element:activation-behaviour
> Implement activation behavior for <summary>

- lib/jsdom/living/nodes/HTMLProgressElement-impl.js
- lib/jsdom/living/nodes/HTMLProgressElement.webidl
- test/web-platform-tests/to-run.yaml
`<progress>` was previously a stub.
Spec: https://html.spec.whatwg.org/multipage/form-elements.html#the-progress-element
> Implement the <progress> element

- lib/jsdom/living/helpers/form-controls.js
- test/web-platform-tests/to-run.yaml
It should look for a child of the disabled `<fieldset>` rather than a descendant.
> Fix handling of <legend> in disabled <fieldset>

- lib/jsdom/living/helpers/focusing.js
- test/web-platform-tests/to-run.yaml
- test/web-platform-tests/to-upstream/html/interaction/focus/tabindex-focus-flag-dont-upstream.html
...if they are the first `<summary>`-child of a `<details>` element.
> Allow <summary> elements to be focused

- README.md
Signed-off-by: Lucian <lucian.buzzo@gmail.com>
> Fix typos and grammar issues in README

- lib/jsdom/browser/Window.js
- lib/jsdom/browser/resources/per-document-resource-loader.js
- lib/jsdom/living/aborting/AbortSignal-impl.js
- lib/jsdom/living/constraint-validation/DefaultConstraintValidation-impl.js
- lib/jsdom/living/file-api/FileReader-impl.js
- lib/jsdom/living/helpers/events.js
- lib/jsdom/living/helpers/focusing.js
- lib/jsdom/living/helpers/runtime-script-errors.js
- lib/jsdom/living/nodes/Document-impl.js
- lib/jsdom/living/nodes/HTMLDetailsElement-impl.js
- lib/jsdom/living/nodes/HTMLElement-impl.js
- lib/jsdom/living/nodes/HTMLFormElement-impl.js
- lib/jsdom/living/nodes/HTMLFrameElement-impl.js
- lib/jsdom/living/nodes/HTMLInputElement-impl.js
- lib/jsdom/living/nodes/HTMLLabelElement-impl.js
- lib/jsdom/living/nodes/HTMLMediaElement-impl.js
- lib/jsdom/living/nodes/HTMLScriptElement-impl.js
- lib/jsdom/living/nodes/HTMLTextAreaElement-impl.js
- lib/jsdom/living/post-message.js
- lib/jsdom/living/websockets/WebSocket-impl-browser.js
- lib/jsdom/living/websockets/WebSocket-impl.js
- lib/jsdom/living/webstorage/Storage-impl.js
- lib/jsdom/living/window/SessionHistory.js
- lib/jsdom/living/xhr-utils.js
- lib/jsdom/living/xmlhttprequest.js
- test/web-platform-tests/to-run.yaml
This resulted in a pretty large clean-up of the old event code. Fixes https://github.com/jsdom/jsdom/issues/2179.
> Add helpers for creating and firing events

- README.md
Closes #2446.
/cc @pladaria and @Xeppy. Would this documentation have helped you avoid the issue you ran into?
> Document how runScripts installs globals

- README.md
- lib/jsdom/browser/htmltodom.js
- lib/jsdom/browser/parse5-adapter-parsing.js
- lib/jsdom/living/helpers/shadow-dom.js
- lib/jsdom/living/nodes/Document-impl.js
- lib/jsdom/living/nodes/DocumentFragment-impl.js
- lib/jsdom/living/nodes/HTMLTemplateElement-impl.js
- lib/jsdom/living/nodes/Node-impl.js
- lib/jsdom/living/nodes/ShadowRoot-impl.js
- test/api/fragment.js
- test/web-platform-tests/to-run.yaml
* Implement proper template content owner document semantics
* Add missing adoption hooks for the `template` element.
Fix #2041
> Add adoption step and fix document owner for HTMLTemplateElement

- lib/jsdom/living/nodes/HTMLLinkElement-impl.js
- test/web-platform-tests/to-upstream/html/semantics/document-metadata/the-link-element/no-browsing-context.html
> Do not fetch non-browsing-context-connected <link>s

- lib/jsdom/living/index.js
- lib/jsdom/living/window/External.webidl
Following the spec change in https://github.com/whatwg/html/pull/4296.
> Expose the External interface

- package.json
- test/web-platform-tests/to-run.yaml
- test/web-platform-tests/to-upstream/dom/nodes/DocumentFragment-querySelectorAll-after-modification.html
- test/web-platform-tests/to-upstream/dom/nodes/Node-cloneNode-external-stylesheet-no-bc.sub.html
- test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelectorAll-removed-elements.html
- test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelectors-exclusive.html
- yarn.lock
These close four "maybe fixed (add tests to confirm)" issues. I've confirmed locally that they all fail before the relevant change or nwsapi version update.
> Some tests

- lib/jsdom/living/nodes/HTMLElement-impl.js
- test/web-platform-tests/to-run.yaml
- test/web-platform-tests/to-upstream/html/editing/activation/click-bail-on-disabled.html
> Fix disabled elements never again being .click()able

- test/web-platform-tests/to-upstream/dom/nodes/Element-matches-namespaced-elements.html
> Add test of matches() and namespaced elements

- test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-scope.html
> Add test for :scope selector in querySelector(All)

- lib/jsdom/living/helpers/strings.js
- lib/jsdom/living/nodes/Element-impl.js
- test/web-platform-tests/to-run.yaml
https://dom.spec.whatwg.org/#element-html-uppercased-qualified-name
> Use ASCII uppercase for tagName

- lib/jsdom/living/nodes/ElementCSSInlineStyle-impl.js
- lib/jsdom/living/nodes/HTMLElement-impl.js
- lib/jsdom/living/nodes/SVGElement-impl.js
- test/web-platform-tests/to-upstream/svg/element.html
Hi, 
I bumped into this small bug when trying to parse an SVG with inline styles using DOMParser. I'm far from an expert on jsdom, but I managed to do a quick fix.
Let me know if you need any more info.
Cheers,
Karel
> added _attributeModified for style in SVGElementImpl

- test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-case-insensitive.html
> Add test to querySelector to be case insensitive

- lib/jsdom/living/nodes/HTMLMediaElement-impl.js
> addNextTrack -> addTextTrack

- package.json
- test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelectors-namespaces.html
- yarn.lock
> Bump nwsapi minimum version and add namespace selector test

- .eslintrc.json
- package.json
- yarn.lock
This in particular lets us tighten up the loosening introduced in 0b7dba807f661170346bfada9b08ae26aa865512.
> Update ESLint dependency

- README.md
> fix README web worker link

- .eslintrc.json
- lib/jsdom/browser/parser/xml.js
- package.json
- yarn.lock
> Upgrade to saxes 4.0.2.

- lib/jsdom/living/nodes/Comment-impl.js
- lib/jsdom/living/nodes/Text-impl.js
- test/web-platform-tests/to-upstream/dom/nodes/Comment-constructor.html
- test/web-platform-tests/to-upstream/dom/nodes/Text-constructor.html
Add support for optional data parameter for Comment and Text constructors.
Fixes #2273.
> Fix incorrect Comment and Text constructors

- README.md
This was missed in 3a4fd6258e6b13e9cf8341ddba60a06b9b5c7b5b.
> Fix documentation on globals installed on window

- lib/jsdom/browser/Window.js
- test/api/from-outside.js
- test/web-platform-tests/to-run.yaml
- test/web-platform-tests/to-upstream/html/webappapis/animation-frames/nested-raf-not-sync.html
- test/web-platform-tests/to-upstream/html/webappapis/timers/errors.html
This setup follows the spec more, is a lot simpler to follow, fixes #2800, and fixes #2617.
> Re-do animation frame and timer callbacks

- lib/jsdom/living/helpers/form-controls.js
- lib/jsdom/living/helpers/number-and-date-inputs.js
- lib/jsdom/living/helpers/strings.js
- lib/jsdom/living/nodes/HTMLInputElement-impl.js
- lib/jsdom/living/nodes/HTMLMeterElement-impl.js
- lib/jsdom/living/nodes/HTMLProgressElement-impl.js
This is rebased on top of #2786. Creating a draft for Travis to take a look at it first.
> Final clean-ups in <input>

- lib/jsdom/living/helpers/strings.js
- lib/jsdom/living/nodes/HTMLSelectElement-impl.js
- lib/jsdom/living/nodes/HTMLTableCellElement-impl.js
> Add rules for parsing integers and non-negative integers

- lib/jsdom/vm-shim.js
This should’ve been done in <https://github.com/jsdom/jsdom/pull/2743>.
> fix(vm‑shim): Use `js‑globals.json`

- lib/jsdom/living/helpers/style-rules.js
- test/web-platform-tests/to-upstream/cssom/getComputedStyle-visibility-inheritance-inline.html
> fix(getComputedStyle): consider inline styles in inheritance

- lib/jsdom/level2/style.js
- lib/jsdom/living/cssom/StyleSheetList-impl.js
- lib/jsdom/living/cssom/StyleSheetList.webidl
- lib/jsdom/living/helpers/style-rules.js
- lib/jsdom/living/helpers/stylesheets.js
- lib/jsdom/living/interfaces.js
- lib/jsdom/living/nodes/Document-impl.js
- scripts/webidl/convert.js
Part of https://github.com/jsdom/jsdom/issues/2727.
> refactor(StyleSheetList): Use implementation and generated wrapper

- test/api/encoding.js
Currently, `test/api/encoding.js` depends&nbsp;on&nbsp;the&nbsp;undeclared `pn/fs`&nbsp;dependency.
https://github.com/jsdom/jsdom/blob/b4b5a542380316a0d7296f7f41a5909bf5e097db/test/api/encoding.js#L2
This&nbsp;is&nbsp;disallowed by&nbsp;[**pnpm**](https://pnpm.js.org) and&nbsp;will&nbsp;be&nbsp;disallowed by&nbsp;[**Yarn&nbsp;v2**](https://yarnpkg.com/).
---
See also: <https://github.com/jsdom/jsdom/pull/2783>
> test(api/encoding): Use `fs.promises`

- lib/jsdom/living/nodes/HTMLInputElement-impl.js
- test/web-platform-tests/to-upstream/html/semantics/forms/the-input-element/input-step-float.html
> Use Decimal.js more consistently in <input>

- package.json
- test/web-platform-tests/to-upstream/dom/events/EventTarget-add-listener-platform-object.html
- yarn.lock
Fixes #2869.
---
<del>Draft until https://github.com/jsdom/webidl2js/pull/182 gets merged and released.</del>
> Update dependencies and add test for #2869

- lib/jsdom/browser/resources/resource-loader.js
- test/api/resources.js
> Fix trying to abort data URL requests

- lib/jsdom/browser/Window.js
- lib/jsdom/living/interfaces.js
- lib/jsdom/living/nodes/HTMLElement.webidl
- lib/jsdom/living/nodes/HTMLUnknownElement.webidl
- lib/jsdom/living/nodes/SVGElement.webidl
- lib/jsdom/living/nodes/SVGGraphicsElement.webidl
- lib/jsdom/living/nodes/SVGSVGElement.webidl
- lib/jsdom/living/nodes/XMLDocument.webidl
- lib/jsdom/living/svg/SVGAnimatedString.webidl
- lib/jsdom/living/svg/SVGNumber.webidl
- lib/jsdom/living/svg/SVGStringList.webidl
This is necessary since <https://github.com/jsdom/webidl2js/pull/191> and <https://github.com/jsdom/webidl2js/pull/192>.
---
review?(@domenic, @TimothyGu)
> Add missing `[Exposed]` extended attributes

- lib/jsdom/living/events/Event.webidl
- lib/jsdom/living/nodes/CharacterData.webidl
- lib/jsdom/living/nodes/DOMImplementation.webidl
- lib/jsdom/living/nodes/DOMStringMap.webidl
- lib/jsdom/living/nodes/Document.webidl
- lib/jsdom/living/nodes/Element.webidl
- lib/jsdom/living/nodes/GlobalEventHandlers.webidl
- lib/jsdom/living/nodes/HTMLBodyElement.webidl
- lib/jsdom/living/nodes/HTMLElement.webidl
- lib/jsdom/living/nodes/HTMLFontElement.webidl
- lib/jsdom/living/nodes/HTMLFormElement.webidl
- lib/jsdom/living/nodes/HTMLFrameElement.webidl
- lib/jsdom/living/nodes/HTMLIFrameElement.webidl
- lib/jsdom/living/nodes/HTMLImageElement.webidl
- lib/jsdom/living/nodes/HTMLInputElement.webidl
- lib/jsdom/living/nodes/HTMLObjectElement.webidl
- lib/jsdom/living/nodes/HTMLTableCellElement.webidl
- lib/jsdom/living/nodes/HTMLTableElement.webidl
- lib/jsdom/living/nodes/HTMLTableRowElement.webidl
- lib/jsdom/living/nodes/HTMLTextAreaElement.webidl
- lib/jsdom/living/nodes/ShadowRoot.webidl
- lib/jsdom/living/window/Location.webidl
- package.json
- yarn.lock
I’ve also added the header link comments to **WebIDL** files that were modified in this PR and that didn't have them before to match the rest of the repository.
> Align with WebIDL extended attribute renames

- lib/jsdom/living/nodes/HTMLInputElement-impl.js
- test/web-platform-tests/to-run.yaml
Related review: https://github.com/jsdom/jsdom/pull/2951#discussion_r419025954
> Fix the valueMissing check of radio

- lib/jsdom/living/nodes/HTMLButtonElement-impl.js
- lib/jsdom/living/nodes/HTMLElement-impl.js
- test/web-platform-tests/to-run.yaml
Original commit: https://github.com/jsdom/jsdom/commit/d5b4fcb81c974321c713ec89bc97ae60d5802b75
Related review: https://github.com/jsdom/jsdom/pull/2951#discussion_r419037236
> fix: translate, draggable, and type ASCII case insensitivity.

- lib/jsdom/living/nodes/Document-impl.js
- test/web-platform-tests/to-upstream/html/interaction/focus-managment/focused-area-removal.html
> fix(focus): Removing the activeElement keeps the document focused

- lib/jsdom/living/helpers/custom-elements.js
Avoids backup queue leak, per https://github.com/whatwg/html/issues/6385.
> Dequeue CE queue elements while processing them

- lib/jsdom/living/events/InputEvent-impl.js
- lib/jsdom/living/events/InputEvent.webidl
- test/web-platform-tests/to-upstream/uievents/constructors/inputevent-constructor.html
> Support inputType on InputEvent

- lib/jsdom/browser/Window.js
- lib/jsdom/living/helpers/document-base-url.js
- lib/jsdom/living/nodes/Document-impl.js
- lib/jsdom/living/nodes/HTMLFrameElement-impl.js
- test/web-platform-tests/to-upstream/html/semantics/embedded-content/the-iframe-element/bad-src-means-about-blank.html
Fixes https://github.com/jsdom/jsdom/issues/3107
> Location href in about blank src iframe

- lib/jsdom/browser/resources/resource-loader.js
- test/api/fixtures/from-file/unicode-진 シーン-i 🥰 you.css
- test/api/fixtures/from-file/unicode-진 シーン-i 🥰 you.html
- test/api/from-file.js
> Fix loading of subresources with Unicode filenames

- lib/jsdom/living/nodes/Comment-impl.js
- lib/jsdom/living/nodes/Text-impl.js
- test/web-platform-tests/to-run.yaml
They would not properly assign an owner document
> Fix Text and Comment constructors

- lib/jsdom/browser/parser/html.js
- test/web-platform-tests/to-upstream/domparsing/svg-template.html
> Fix SVG-namespace <template>s

- lib/jsdom/living/nodes/HTMLOutputElement-impl.js
Blocked on:
- https://github.com/web-platform-tests/wpt/pull/28161 plus a WPT roll
- Probably we should wait for https://github.com/whatwg/html/issues/6516 to resolve or we might have to rewrite it again
> Fix <output>'s value and defaultValue

- lib/jsdom/living/nodes/HTMLFormElement-impl.js
- test/web-platform-tests/to-upstream/html/semantics/forms/constraints/using-form-attribute.html
> Check all associated elements for form validity

- test/web-platform-tests/to-run.yaml
Part of: <https://github.com/jsdom/jsdom/issues/3157>
> Convert WPTs in `FileAPI` directory to use the new format

- test/web-platform-tests/to-run.yaml
Part of: <https://github.com/jsdom/jsdom/issues/3157>
> Convert WPTs in `cors` directory to use the new format

- lib/jsdom/living/nodes/ParentNode-impl.js
- lib/jsdom/living/nodes/ParentNode.webidl
- test/web-platform-tests/to-run.yaml
This PR implements and tests [ParentNode.replaceChildren()](https://dom.spec.whatwg.org/#dom-parentnode-replacechildren).
Closes #3102.
New contributor here; sorry if I missed anything obvious.
> Add ParentNode.replaceChildren()

- test/to-port-to-wpts/level2/html.js
> Fix typo in level2/html.js

- lib/jsdom/living/helpers/style-rules.js
- test/web-platform-tests/to-upstream/cssom/getComputedStyle-visibility-nominal-case-inline.html
- test/web-platform-tests/to-upstream/cssom/getComputedStyle-visibility-nominal-case.html
Hello guys,
This PR is linked to the issue https://github.com/jsdom/jsdom/issues/3182.
For now I don't have made tests. But I would like to. But I can't launch test in local, linux... :(
> Do not override propertyValue in getCascadedPropertyValue if ""

- test/karma-webworker.conf.js
- test/karma.conf.js
- test/web-platform-tests/to-run.yaml
> Fix browser tests by enabling SharedArrayBuffer

- lib/jsdom/level2/style.js
> Fix typo in style.js

- lib/jsdom/living/aborting/AbortController-impl.js
- lib/jsdom/living/aborting/AbortController.webidl
- lib/jsdom/living/aborting/AbortSignal-impl.js
- lib/jsdom/living/aborting/AbortSignal.webidl
- test/web-platform-tests/to-run.yaml
> Add AbortSignal.reason

- lib/jsdom/living/events/EventTarget-impl.js
- lib/jsdom/living/events/EventTarget.webidl
- test/web-platform-tests/to-run.yaml
> Add support for AbortSignal in addEventListener

- lib/jsdom/living/interfaces.js
- lib/jsdom/living/nodes/HTMLFormControlsCollection-impl.js
- lib/jsdom/living/nodes/HTMLFormControlsCollection.webidl
- lib/jsdom/living/nodes/HTMLFormElement-impl.js
- lib/jsdom/living/nodes/RadioNodeList-impl.js
- lib/jsdom/living/nodes/RadioNodeList.webidl
- test/web-platform-tests/to-run.yaml
https://github.com/jsdom/jsdom/issues/2600
> implement HTMLFormControlsCollection and RadioNodeList

- package.json
Unpinned in 2e355263e5cae2e4647b0956f777c0abd2c62d5b
> chore: remove false comment

- lib/api.js
- lib/jsdom/living/helpers/http-request.js
- test/api/from-url.js
- test/chai-helpers.js
Extracted from #3393.
Co-authored-by: LungZeno <lungzenoopen@gmail.com>
> Fix JSDOM.fromURL() bugs in the browser build

- lib/jsdom/living/nodes/HTMLInputElement-impl.js
- lib/jsdom/living/nodes/HTMLTextAreaElement-impl.js
- test/web-platform-tests/to-run.yaml
- test/web-platform-tests/to-upstream/html/semantics/forms/the-textarea-element/setRangeText.html
> fix: proper end index in setRangeText() for input and textarea

- lib/jsdom/living/geometry/DOMRect-impl.js
- lib/jsdom/living/geometry/DOMRect.webidl
- lib/jsdom/living/geometry/DOMRectReadOnly-impl.js
- lib/jsdom/living/geometry/DOMRectReadOnly.webidl
- lib/jsdom/living/interfaces.js
- scripts/webidl/convert.js
- test/web-platform-tests/to-run.yaml
Extracted from #2926. Part of #2716.
> Implement DOMRect and DOMRectReadOnly

- .github/workflows/jsdom-ci.yml
They seem to have fixed the relevant vm bugs.
> Include Node.js v20 in CI

- README.md
Pros:
- For each example, the HTML is exactly the same, allowing the reader to focus on what matters: the effect of different `runScripts` values.
- When a `<script>` is a noop, `0` is logged instead of `1`. IMO, this is more intuitive and reduces cognitive load.
- The examples can be copied and pasted elsewhere and, without modification, output useful information. Before, the last line of each example was something like `x === y`, which won't always show output (e.g., running in a test framework). 
Cons:
- The examples are longer
- I added `<div id="content"></div>` into the body to separate script elements from script outcomes. This might make the HTML harder to read.
> Changed examples within the "Executing scripts" section

- lib/jsdom/living/aria/ARIAMixin.webidl
- lib/jsdom/living/custom-elements/ElementInternals-impl.js
- lib/jsdom/living/custom-elements/ElementInternals.webidl
- lib/jsdom/living/nodes/Element-impl.js
- lib/jsdom/living/nodes/Element.webidl
- scripts/webidl/convert.js
- test/web-platform-tests/to-run.yaml
For both Element and ElementInternals. Closes #3561. Closes #3586. Partially addresses #3323.
> Implement string ARIA reflection

- lib/jsdom/living/nodes/HTMLInputElement-impl.js
- lib/jsdom/living/nodes/HTMLInputElement.webidl
- lib/jsdom/living/nodes/HTMLProgressElement-impl.js
- lib/jsdom/living/nodes/HTMLProgressElement.webidl
- lib/jsdom/living/nodes/HTMLTableCellElement.webidl
- lib/jsdom/living/nodes/HTMLTableColElement.webidl
- lib/jsdom/living/nodes/HTMLTextAreaElement-impl.js
- lib/jsdom/living/nodes/HTMLTextAreaElement.webidl
- scripts/webidl/convert.js
This gives slight improvements to correctness on various elements, but mostly is designed to reduce hand-written code.
> Implement the remaining types of numeric reflection

- test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-All-comma-selector.html
> Add regression test for comma selector

- .github/workflows/jsdom-ci.yml
Increase test ci matrix to include node 22
Before:
Node 18, 20, 20 ([latest](https://www.npmjs.com/package/node?activeTab=versions))
After:
Node 18, 20, 22
> add node 22 to test ci matrix

- .github/workflows/jsdom-ci.yml
- package-lock.json
- package.json
Add support for canvas v3 in addition to v2 and setup the tests to run with both versions.
> Add support for canvas v3

- lib/jsdom/living/helpers/http-request.js
- test/api/from-url.js
> Catch invalid redirect URLs

- Contributing.md
@hesxenon, what do you think of this?
> Document WPTs and to-run.yaml better

- test/web-platform-tests/to-upstream/cookies/set-and-delete-document-cookie.window.js
> Add a test for cookie deletion via past expiration

- lib/jsdom/living/nodes/Element-impl.js
- lib/jsdom/living/nodes/HTMLOrSVGElement-impl.js
- lib/jsdom/living/nodes/Node-impl.js
See individual commits for details.
Part of #3154.
> Defer creation of not-accessed complex objects

- benchmark/selectors/sizzle.js
Removed a test that was kept for comparison.
Added a new test to measure the performance of `querySelector()`.
> Add querySelector() benchmark test

- package-lock.json
- package.json
- test/web-platform-tests/to-upstream/html/semantics/forms/the-select-element/select-defineProperty.html
> Roll webidl2js and add a test for the defineProperty bug

- test/web-platform-tests/to-upstream-expectations.yaml
- test/web-platform-tests/to-upstream/css/cssom/style-backgroundcolor-table-row.html
- test/web-platform-tests/to-upstream/css/selectors/attribute-selector-escape.html
- test/web-platform-tests/to-upstream/css/selectors/focus-within.html
- test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelectorAll-namespace.html
Fix #1965, fix #3055, fix #1587
> Add more tests

- package-lock.json
- package.json
We can't yet update whatwg-url until we roll WPTs.
> Update most dependencies and dev dependencies

- test/web-platform-tests/to-upstream-expectations.yaml
- test/web-platform-tests/to-upstream/css/cssom/style-set-property.html
Related https://github.com/jsdom/cssstyle/pull/190
* See https://github.com/jsdom/cssstyle/issues/189
* See https://github.com/jsdom/cssstyle/issues/196
> Add failing test for cssstyle issues

- test/web-platform-tests/to-upstream-expectations.yaml
- test/web-platform-tests/to-upstream/css/cssom/style-global-variable.html
- test/web-platform-tests/to-upstream/css/cssom/style-set-custom-property.html
Add regression tests for #3833, #3878
> Add regression tests related to jsdom/cssstyle

- test/web-platform-tests/to-upstream-expectations.yaml
- test/web-platform-tests/to-upstream/css/cssom/style-font-shorthand.html
Ref https://github.com/jsdom/jsdom/issues/3021
> Add test for font shorthand

- test/web-platform-tests/to-upstream-expectations.yaml
- test/web-platform-tests/to-upstream/css/cssom/style-color-values.html
Regression test for https://github.com/jsdom/jsdom/issues/3887
> Add regression test for specified and resolved values of color

- test/web-platform-tests/to-upstream-expectations.yaml
- test/web-platform-tests/to-upstream/css/css-images/gradient-specified-values.html
https://github.com/jsdom/cssstyle/pull/232
> Regression test for cssstyle

- test/web-platform-tests/to-upstream-expectations.yaml
- test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelectorAll-scope-change.html
Regression test for https://github.com/jsdom/jsdom/issues/3906
> Regression test with changing the scope

- test/web-platform-tests/to-run.yaml
Related: https://github.com/jsdom/jsdom/issues/3895
> Add css/css-display tests

- test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-nested.html
> Add regression test
