jsdom/jsdom

lib/jsdom/utils.js, test/living-html/location.js, test/window/history.js
This fixes our url resolution which was broken since ea8f5bf0b5d29fa32376e14f2e7dd6fb4b02e63a.
I plan to implement the [url resolution algorithm](https://url.spec.whatwg.org/#concept-basic-url-parser) sometime soon(tm), but we need a fix until then, especially for the 3.x release cycle before the window rework.
This should make #1009 closeable.
=> Fix url resolution

package.json, test/browser-runner.js
- Upgrade local selenium-standalone package to the latest version. This now requires a two-step installation/start process.
- Use get-saucelabs-browsers to ensure we are always testing the latest stable Chrome version. This is apparently necessary since Sauce Labs does not have any way of doing so with a simple parameter like "stable".
- Upgrade all other packages to their latest versions, being sure to pin < 1.0.0 packages unless I've received confirmation from the author that they will not be breaking back-compat on patch versions.
=> Various upgrades to deps and browser CI infrastructure

lib/jsdom.js, lib/jsdom/browser/Window.js, lib/jsdom/level1/core.js
This reduces init times by about 600+% if scripting on the page is not needed, so gives a nice performance boost.
This breaks backwards compat somewhat!
Enabling scripting after already having received a window (i.e. adding ProcessExternalResources to document.implementation manually, not providing it in config/options) results in a changing document.defaultView.
If we need to increase major probably mainly depends on if document.implementation._addFeature is considered public API.
=> Defer the initialization of vm

lib/jsdom/browser/htmltodom.js, test/jsdom/parsing.js
JSDOM 3.0 started implementing DocumentType as per the spec and return the correct type when queried using document.doctype. However, there's a bug in the parsing code and simple doctypes of the form '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">' aren't getting properly parsed.
As a result there's no way for application to implement their own doc type parsing (which I used to do for 2.0) or get correct values from JSDOM.
=> Bug in doctype parsing

lib/jsdom/level2/html.js, test/living-html/htmlelement.js, test/runner, test/worker-runner.js
All elements with unrecognized tags are created with HTMLUnknownElement instead of HTMLElement.
Also changed this to only occur on HTMLDocument since we need to start to split these up properly.
=> Add HTMLUnknownElement

lib/jsdom/browser/Window.js, lib/jsdom/level1/core.js, lib/jsdom/level2/html.js, test/window/frame.js
Whenever an frame/iframe node element is created, there is a associated getter created for the parent window. However, the getter is not cleaned up when the node is removed. Also, `window.frames.length` or `window.length` doesn't change after iframes are removed.
The issue can be reproduced [here](https://gist.github.com/sylnp0201/1922dc0304998363a20d) with jsdom v3.1.2 and a simple Backbone view.
=> Iframes are not cleaned up after the node DOMs are removed

lib/jsdom/level1/core.js, lib/jsdom/living/index.js, lib/jsdom/living/parent-node.js, test/living-dom/files/parent-node.html, test/living-dom/parent-node.js, test/runner
https://dom.spec.whatwg.org/#interface-parentnode
Fixes #519
* `children` should only be defined on `Document`, `Element` and `DocumentFragment`
* `children` should be a HTMLColleciton
* Implement firstElementChild
* Implement lastElementChild
* Implement childElementCount
There's more stuff in ParentNode, but as far as I can tell there is not yet a single browser which implements those. So I would rather wait (perhaps the api is not yet stable)
=> Implement ParentNode interface

.jscsrc, .jshintignore, test/w3c/index.js, test/w3c/w3ctest.js
Required fixing a bug in w3ctest.js which would replace both <script> tags with our shim, instead of just the reporter. We did this in a more principled way by overriding the resourceLoader.
Fixes #1117.
=> Add web-platform-tests NodeIterator tests

README.md, lib/jsdom/virtual-console.js, test/jsdom/virtual-console.js
I noticed a possible shorthand when dealing with the virtual console and wanted to propose it here.
This PR makes `VirtualConsole.sendTo` return `this` so that you can write the shorthand:
```
jsdom.env("<p></p>", {
virtualConsole: jsdom.createVirtualConsole().sendTo(console)
done: function (err, window) {}
});
```
It also updates one place in the README to illustrate how it's done.
=> Return instance from virtualConsole.sendTo

benchmark/dom/index.js, benchmark/dom/named-properties.js, lib/jsdom/living/named-properties-window.js, lib/jsdom/named-properties-tracker.js, lib/jsdom/utils.js, package.json, test/jsdom/named-properties-tracker.js, test/living-html/named-properties-window.js
This was one of the thing slowing down #1156 (w3c/respec#453).
The included benchmark has these results:
before: `jsdom  x 0.19 ops/sec ±68.89% (5 runs sampled)`
after: `jsdom  x 3,054 ops/sec ±7.63% (29 runs sampled)`
The named property tracker has been refactored by making the tracking and untracking more explicit. The tracker now keeps a list of potential values for a specific named property. The resolver function that is used for the `window` no longer walks the entire tree, but receives that list of potential values. It can then filter on that list and sort it in tree order using `compareDocumentPosition`. This works fast because `compareDocumentPosition` has been optimized in #1169.
=> Optimize the named property tracker by not walking the entire tree

lib/jsdom/browser/Window.js, lib/jsdom/browser/resource-loader.js, lib/jsdom/level2/html.js, lib/jsdom/level2/style.js, lib/jsdom/living/index.js, lib/jsdom/living/url.js, lib/jsdom/utils.js, package.json, test/jsdom/index.js, test/level2/html.js, test/level2/style.js, test/misc/url.js, test/runner, test/sizzle/index.js, test/w3c/w3ctest.js, test/window/history.js, test/window/script.js, test/worker-runner.js
I was working with JSDom and ran into some behavior with `myAnchorTag.pathname` that I thought was unexpected. Let me show an example:
```js
global.jsdom = require('jsdom').jsdom;
global.document = jsdom('<html><head><script></script></head><body></body></html>');
global.window = global.document.parentWindow;
global.navigator = window.navigator = { userAgent: 'JSDom', appVersion: '' };
var a = document.createElement('a');
a.href = "uri/what/pls";
a.pathname;
// /what/pls
a.href = "/uri/what/pls";
a.pathname;
// /uri/what/pls
```
Is it unexpected that the pathname always strips the first part of the path when it is relative + no leading slash? Or am I missing something obvious here? :open_mouth:
=> Pathname of anchor tag with relative `href`

lib/jsdom/browser/Window.js, test/living-html/cookie.js, test/misc/xhr-file-urls.js, test/runner, test/worker-runner.js
Closes #1180.
Please review @justinmchase. I was unable to write a test showing that getResponseHeader throws as long as the file URL was two-slashes only.
=> Fix XHR for file URLs by working around node-XHR bug

.jshintrc, README.md, lib/jsdom.js, lib/jsdom/browser/Window.js, lib/jsdom/virtual-console.js, test/jsdom/virtual-console.js, test/living-html/on-error.js
I also threw in a commit that classes up virtual-console.js.
=> Fix #1119: virtualConsole.sendTo should send jsdomErrors to console.error by default

README.md
makes it easier to understand why jsdom won't work with node.js and should reduce questions like #1187, #1145, #1081
=> explanation why io.js instead of node.js in readme

lib/jsdom/utils.js, package.json, test/w3c/w3ctest.js, test/worker-runner.js
This fixes certain base URL tests I am soon hoping to add, which use hrefs like "/foo/bar.html" that don't work very well on the file system.
In theory we should be running their python server. But, it requires modifying your hosts file, which is pretty sad. We can just do this hack until we run in to the need to run tests that require that level of complexity.
=> Always run web platform tests from a server

lib/jsdom/level1/core.js, lib/jsdom/level2/core.js, lib/jsdom/level2/html.js, lib/jsdom/living/attributes.js, lib/jsdom/living/html-collection.js, lib/jsdom/living/index.js, lib/jsdom/living/named-properties-window.js, lib/jsdom/living/node-list.js, lib/jsdom/living/parent-node.js, lib/jsdom/living/selectors.js, lib/jsdom/utils.js, test/browser/index.js, test/level1/core.js, test/level2/html.js, test/living-dom/node-list.js, test/runner, test/worker-runner.js
- Removes all non-public properties and methods, in the process fixing #1224.
- Removes NodeList's no-op length setter, fixing #859. It was only used so that we could call Array.prototype.push on it; instead we manually copy over nodes.
- Removes their public constructors.
- Removes the inheritance relationship between them, which is incorrect.
- Removes HTMLOptionsCollection, which was just an alias for HTMLCollection. We'll use HTMLCollection instead, for now.
=> Re-do NodeList and HTMLCollection

lib/jsdom.js, lib/jsdom/level1/core.js, package.json, test/level2/html.js, test/living-html/cookie.js
This enables correct execution of code like `document.cookie = 'foo'`.
Blocked on either https://github.com/request/request/pull/1811 or https://github.com/SalesforceEng/tough-cookie/pull/56.
=> Implement loose cooking parsing

.travis.yml
This used to work :-/. Might need to disable them.
=> Travis browser builds are broken, only for PRs from forks I think

README.md
Commit 2184995dc6531cb92d219497c8f88c9b7f088bc1 stated that jsdom
7.0.0 "requires Node.js 4 or newer", but the URL for Changelog.md
was still pointing to 4.0.0.
=> Update link to Changelog.md in README.md

lib/jsdom/living/filelist.js
The correct file containing the symbols for filellist.js is filelist-symbols, not file-symbols.
=> Fix typo in symbols file name

lib/jsdom/browser/htmltodom.js, test/jsdom/parsing.js
Serialising `math` elements generates a namespace declaration with `:xmlns` instead of `xmlns`.
Example code:
```js
var jsdom = require('jsdom');
var html = '<!DOCTYPE html><math xmlns="http://www.w3.org/1998/Math/MathML"></math>';
jsdom.env(html, (err, window) => {
if (err) return console.error('ERROR: ' + err);
console.log(jsdom.serializeDocument(window.document));
});
```
Output:
```html
<!DOCTYPE html><html><head></head><body><math :xmlns="http://www.w3.org/1998/Math/MathML"></math></body></html>
```
=> Regression with serialisation of <math>

lib/jsdom/utils.js, test/jsdom/resource-loading.js, test/jsdom/utils.js
I wasn't sure where to put a test so I created a new `misc/utils` file. Let me know if there's a more appropriate place.
=> Make base64 contents optional in data urls

lib/jsdom/browser/Window.js, test/web-platform-tests/index.js, test/web-platform-tests/run-to-upstream-web-platform-test.js, test/web-platform-tests/run-web-platform-test.js, test/web-platform-tests/to-upstream/html/webappapis/timers/arguments.html, test/web-platform-tests/to-upstream/html/webappapis/timers/errors.html
Only read up on the spec a tiny bit (until I dive into the Window rework), but this should be a pretty nice fix for #1291, going mostly by rudimentary behaviour here.
Spec says
> Create a script using script source as the script source, the URL where script source can be found, and settings object as the environment settings object.
I'm not sure if the url there means that stack traces should spit out that url as the source, but added that with a nice trick. We'll never get the stacktrace as a whole correct I think, sadly.
@domenic You think this would suffice?
=> Fix setTimeout for string attributes

lib/jsdom/living/events/Event-impl.js, lib/jsdom/living/events/EventTarget-impl.js, lib/jsdom/living/nodes/Document-impl.js, test/web-platform-tests/to-upstream/dom/events/EventTarget-add-remove-listener.html
```javascript
var jsdom = require("jsdom");
jsdom.env(
"<p id='test'></p>",
function (err, window) {
var ticks = 0,
listener = function() { ticks++ },
elm = window.document.getElementById('test');
// Attach 
elm.addEventListener('test', listener, false);
// Dispatch
event = new window.CustomEvent('test');
elm.dispatchEvent(event);
console.log(ticks); // 1
// Detach
elm.removeEventListener('test', listener);
// Dispatch
event = new window.CustomEvent('test');
elm.dispatchEvent(event);
console.log(ticks); // 2 (should be 1)
}
);
```
Bad behavior with those values:
```javascript
elm.addEventListener('test', listener, false);
elm.removeEventListener('test', listener);
elm.addEventListener('test', listener);
elm.removeEventListener('test', listener, false);
elm.addEventListener('test', …
```
=> removeEventListener doesn't work when useCapture is specified

test/web-platform-tests/index.js, test/web-platform-tests/run-to-upstream-web-platform-test.js, test/web-platform-tests/run-web-platform-test.js
PRing this to see if Travis likes it:
This is due to a regression in Node's HTTP parser that makes it less capable than browsers: https://github.com/nodejs/http-parser/issues/281. Closes #1380. We probably won't be able to fix this until Node either fixes the regression or makes HTTP header parsing customizable.
=> Disable tests that now fail on Node 5.6.0

lib/jsdom/living/events/EventTarget-impl.js, test/web-platform-tests/to-upstream/dom/events/EventTarget-this-of-listener.html
Leave `callback` a reference to the object, and only check for `handleEvent` method at invoke time.
=> Fix #1382: this inside event listener object handleEvent was wrong

lib/jsdom/living/nodes/HTMLLabelElement-impl.js, test/web-platform-tests/to-upstream/html/semantics/forms/the-label-element/proxy-click-to-associated-element.html
Clicking on a label element should trigger activation on an associated element via the `for` attribute linking, or simple nesting (if the associated element meets the [labeling criteria](https://html.spec.whatwg.org/multipage/forms.html#the-label-element:the-label-element-10)).
I would also like to note that I tried very hard to get the `NodeIterator` API to work, but it doesn't seem to be hooked up, unfortunately.
=> Add click proxy behavior for label elements

.eslintignore, lib/jsdom.js, lib/jsdom/browser/documentfeatures.js, lib/jsdom/browser/htmltodom.js, lib/jsdom/living/domparsing/DOMParser-impl.js, lib/jsdom/living/domparsing/DOMParser.idl, lib/jsdom/living/index.js, lib/jsdom/living/nodes/HTMLFrameElement-impl.js, lib/jsdom/living/nodes/XMLDocument-impl.js, lib/jsdom/living/nodes/XMLDocument.idl, lib/jsdom/living/xmlhttprequest.js, scripts/webidl/convert.js, test/jsdom/parsing.js, test/level1/core/files/hc_nodtdstaff.xml.js, test/web-platform-tests/index.js, test/web-platform-tests/to-upstream.js, test/web-platform-tests/to-upstream/domparsing/DOMParser-dont-upstream.html
@Sebmaster I was hoping you could take a look at this. The problem comes with the "add strict parsing errors when parsing XML documents" commit. Flipping that causes a bunch of tests to start failing for weird reasons having to do with tree construction in htmltodom.js. The last commit modifies the web platform tests manifest so that it only runs the tests which have shown failures.
What's weird is that the failures are due to stuff that should have nothing to do with strict vs. non-strict XML parsing. It's something about how nodes are emitted and what's on the stack at that time. I figure since you plugged in sax in the first place maybe you had some ideas.
=> Some work on DOMParser; needs help

lib/jsdom/living/nodes/HTMLFormElement-impl.js, test/jsdom/misc.js
This logic was backwards, throwing errors when `event.preventDefault()` was called on a form submit event:
```
Error: Not implemented: HTMLFormElement.prototype.submit
```
When `event.preventDefault()` was **not** called, no error was logged.
=> Submitting form elements should log errors if and only if not cancelled

lib/jsdom/living/events/EventTarget-impl.js, test/web-platform-tests/to-upstream.js, test/web-platform-tests/to-upstream/dom/events/AddEventListenerOptions-once.html
Don't use array indexes from snapshot since we're modifying in-loop
A minor bug in how "once" event handlers are removed. I've cloned and modified a web platform test to trigger the problem.
=> Fix EventListener once handling

.eslintignore, benchmark/dom/construction.js, lib/jsdom/living/index.js, lib/jsdom/living/node.js, lib/jsdom/living/nodes/CDATASection-impl.js, lib/jsdom/living/nodes/CDATASection.idl, lib/jsdom/living/nodes/Document-impl.js, lib/jsdom/living/nodes/Document.idl, lib/jsdom/living/nodes/Node-impl.js, test/level1/core.js, test/web-platform-tests/to-upstream.js, test/web-platform-tests/to-upstream/dom/nodes/Document-createCDATASection.html, test/web-platform-tests/to-upstream/dom/nodes/Document-createCDATASection.xhtml, test/web-platform-tests/to-upstream/dom/nodes/Document-createComment-createTextNode.js
`document.createCDATASection` missing
1. Says in the spec _"Text that should not be parsed by a parser"_ Where should we test _(i.e. <> ?)_ ?
2. Spec MUST throw exception if NOT html doc. States should be able to derive HTML doc by encoding. How would we like to do this?
- https://dom.spec.whatwg.org/#dom-document-createcdatasection
3. Any idea why MDN says this is deprecated? I DO realize whatwg != w3.org but double checking.
- https://www.w3.org/TR/dom/#cdatasection
- https://developer.mozilla.org/en-US/docs/Web/API/CDATASection
4. Does this mean we have to update web-platform-tests? :face_with_head_bandage:
- (current submodule sha @ c51a023) https://github.com/w3c/web-platform-tests/blob/c51a023bcdf0bf800e46ccfd002a9cf7fcf4f65a/html/dom/interfaces.html#L240
- (current submodule sha @ …
=> ✏️ ✅ 🚀🔧💄 [Fix #1642] `document.createCDATASection` missing

lib/jsdom/browser/Window.js, test/web-platform-tests/to-upstream/html/webappapis/timers/settimeout-setinterval-handles.html
The returned value for `setTimeout()` and `setInterval()` should be numeric non-zero value.
Fixes #1726
=> Align timers with specification

lib/jsdom/browser/Window.js, test/web-platform-tests/to-upstream.js, test/web-platform-tests/to-upstream/html/dom/elements/option/option-element-constructor.html
This adds an Option constructor that adheres to the [current spec for Option constructors](https://html.spec.whatwg.org/#dom-option), available through `jsdom`'s `window`/`defaultView`. 
This has been tested against the specs included in this PR, as well as the real-life use case that led me to raise #1759. 
Please let me know if the location of the tests added to the to-upstream directory are organized correctly.
=> Add Option element constructor

.travis.yml, README.md, lib/jsdom/utils.js
canvas-prebuilt is a package from @chearon https://github.com/chearon/node-canvas-prebuilt, contributor of node-canvas.
Is easier to install for most of the situation and is same as canvas, but prebuilt.
Is a drop in replacement with a different name, i made this PR to enable the us of this package in jsdom.
=> Enable support for canvas-prebuilt package

lib/jsdom.js, test/jsdom/misc.js
When `jsdom.env` is passed a url that does a 302 redirect, any hash on the
url is lost. You can check browser behavior here:
https://httpbin.org/redirect-to?url=https://example.com#hash
<strike>So far, this pull request consists only of a change in the
tests that demonstrates this issue. However, I think I'm making some
progress towards a fix, so hopefully I'll be able to update this once I
find one.</strike>
This change ensures that the url fragment is not lost when a redirect happens.
---
Relevant Specifications (found via [stack overflow](https://stackoverflow.com/questions/2286402/url-fragment-and-302-redirects)):
* https://www.w3.org/TR/cuap#uri
> Suppose that a user requests the resource at http://www.w3.org/TR/WD-ruby/#changes and the server redirects the user agent to …
=> Preserve window.location.hash across redirects

lib/jsdom/living/events/Event-impl.js, test/web-platform-tests/to-upstream.js, test/web-platform-tests/to-upstream/dom/events/Event-stopImmediatePropagation.html
The `stopImmediatePropagation` event seems to be [implemented in jsdom](https://github.com/tmpvar/jsdom/blob/578e2cb3f16c760f26e737299a071ff78ec84589/lib/jsdom/living/events/Event-impl.js#L51). It should stop executing listeners for the same element, but it seems this isn't working as expected in jsdom (this assertion is ok in the browser):
```js
const jsdom = require('jsdom');
const assert = require('assert');
jsdom.env('<html><body></body></html>', (err, window) => {
let i = 0;
const body = window.document.body;
body.addEventListener('test', evt => {
i++;
evt.stopImmediatePropagation();
});
body.addEventListener('test', evt => {
i++;
});
const event = new window.Event('test');
body.dispatchEvent(event);
assert(i === 1);
});
```
On the other hand, `stopPropagation` works fine:
```js …
```
=> Bug: stopImmediatePropagation not working

lib/jsdom/browser/Window.js, test/jsdom/inside-worker-smoke-tests.js
Closes #1732. This worked fine in Node since there clearTimeout does not care what its thisArg is. But in browsers, it does, causing this error.
Thanks @jdthorpe for digging into this until he could produce an isolated test case!!
Will merge after CI signs off.
=> Fix clearTimeout in web workers

lib/jsdom/living/nodes/Element-impl.js, test/web-platform-tests/to-upstream.js, test/web-platform-tests/to-upstream/domparsing/innerhtml-08.html
I have looked at issue #1779, and the problem seems to have been in the innerHTML implementation. The setInnerHTML function includes a specific if-condition rejecting the empty string as input, while browsers seem to handle it. With the if-condition removed the output has been consistent with the way browsers behave, during my limited testing.
I am naturally a bit wary about simply removing a condition since someone must've put it there for a reason in the first place, but perhaps it no longer applies as the codebase has changed. Regardless, I'd appreciate if someone knowing more about the intricacies of innerHTML would chime in.
=> Handle setting innerHTML to the empty string

lib/jsdom/living/xmlhttprequest.js
I spotted this typo and thought we could further make
this error message more helpful.
=> Improve xhr.open not enough args error message

lib/jsdom/living/post-message.js
As stated in the issue, `window.origin` doesn’t exist. This change
allows us to post messages where the origin is something other than `*`.
=> [fix] window.origin doesn't exists (closes #1789)

lib/jsdom/living/nodes/Document-impl.js, lib/jsdom/living/nodes/Document.idl, lib/jsdom/living/nodes/HTMLElement-impl.js, lib/jsdom/living/nodes/HTMLElement.idl, test/web-platform-tests/index.js, test/web-platform-tests/to-upstream.js, test/web-platform-tests/to-upstream/html/dom/elements/global-attributes/dir-attribute.html
Implemented based on https://html.spec.whatwg.org/multipage/dom.html#the-dir-attribute, and tested against other browsers.
As I understand it the directionality logic only comes into play when rendering, so this PR ought to cover all that jsdom needs right now.
=> Implement the global dir attribute and document.dir

README.md, lib/jsdom/browser/documentAdapter.js, lib/jsdom/browser/domtohtml.js, lib/jsdom/browser/htmltodom.js, lib/old-api.md, package.json, test/api/methods.js, test/to-port-to-wpts/misc.js
This PR upgrades parse5 to version 3.0.2, and includes changes to affected tests and documentation. Since the ambitious changes in #1316 have not seen progress for a while, I figured that it'd be better to do this with minimal changes than to remain on such an old version.
I removed three old tests in the misc.js file which were testing the serialization of obsolete DOCTYPEs. From what I've gathered, parse5 removed support for these as they are no longer recognised in the spec.
In addition to the parser changes that have been made, there are also breaking changes to the API's output of `.nodeLocation`. I've updated the tests and documentation to reflect this.
This should resolve #1778 and any other issues which have been due to the old version 🎉
=> Upgrade parse5 to 3.0.2

lib/jsdom/living/html-collection.js
I am seeing a significant performance improvement parsing large documents with this change. When testing on the markup of the full HTML Spec, I saw an average time of 17 seconds drop to 5 seconds.
=> Use Set instead of Array for HTMLCollection keys

lib/jsdom/living/xmlhttprequest.js, test/web-platform-tests/index.js
This tiny two-liner adds support for ArrayBufferViews to be passed to `XMLHttpRequest.prototype.send`.
This makes the XHR more [spec-compliant](https://fetch.spec.whatwg.org/#body-mixin), as ArrayBufferViews are [BufferSources](https://heycam.github.io/webidl/#BufferSource).
=> Support for ArrayBufferViews to XHR::send

lib/jsdom/browser/default-stylesheet.js
See tmpvar/jsdom#1560.
In particular, this helps because it takes out all the selectors that would cause exceptions to be thrown: webkit prefixes in selectors and case-insensitive attribute selectors.
I've tested this patch by running the test that runs slowly with breakpoints set on "all exceptions". There were no exceptions arising from <https://github.com/dperini/nwmatcher/blob/29a1cdc284e330ec6aa38e31c2f02e755a536381/src/nwmatcher-noqsa.js#L765>.
Even though this deletes code, this adds functionality. For example, the rule `-input[type="hidden" i]` would have been ignored before, because nwmatcher doesn't know how to handle ` i`. It would now apply (although type would have to be "hidden", and not "HiDdEn" or "HIDDEN").
This single change improves performance in one of my tests from …
=> Delete webkit prefixes in default CSS

test/web-platform-tests/index.js
I decided to check if any of the disabled tests have been fixed by recent changes, and there are quite a few. I probably won't have to describe the changes in further detail here - the comments on the deleted lines speak for themselves.
=> Enable various web platform tests which are now passing

lib/jsdom/browser/Window.js, lib/jsdom/living/helpers/document-base-url.js, lib/jsdom/living/helpers/selectors.js, lib/jsdom/living/nodes/Element-impl.js, lib/jsdom/living/nodes/ParentNode-impl.js, package-lock.json, package.json
* Deduplicates the addNwmatcher function
* Allows getComputedStyle to use an instance of nwmatcher which doesn't throw exceptions, which brings speed benefits. This closes #1560.
* Fixes #1740 by pulling in the fix for dperini/nwmatcher#103.
* Removes unnecessary "internal querySelector" functionality; we have the impl/wrapper split now to help with that sort of thing.
=> Update nwmatcher, and tweak its options and usage

lib/api.js, lib/jsdom/living/helpers/document-base-url.js, lib/jsdom/living/helpers/stylesheets.js, lib/jsdom/living/nodes/Document-impl.js, lib/jsdom/living/nodes/HTMLBaseElement-impl.js, lib/jsdom/living/nodes/HTMLFrameElement-impl.js, lib/jsdom/living/nodes/HTMLHyperlinkElementUtils-impl.js, lib/jsdom/living/nodes/HTMLLinkElement-impl.js, lib/jsdom/living/window/History-impl.js, lib/jsdom/living/window/Location-impl.js, lib/jsdom/living/window/navigation.js, lib/jsdom/utils.js, lib/old-api.js, package-lock.json, package.json, test/web-platform-tests/index.js, test/web-platform-tests/to-upstream.js, test/web-platform-tests/to-upstream/html/browsers/browsing-the-web/navigating-across-documents/javascript-url-side-effects.html
This makes the navigation work more like the spec.  What I’m hoping to do is get to the point where there is a clear place to hook in and handle navigation that involves creating a new dom instance, without requiring a full re-implementation of “Location” and “History”.
=> Make navigation work more like spec

lib/jsdom/browser/Window.js, lib/jsdom/living/nodes/Document-impl.js, lib/jsdom/living/nodes/Document.idl, lib/jsdom/living/window/External-impl.js, lib/jsdom/living/window/External.idl, test/web-platform-tests/index.js, test/web-platform-tests/to-upstream.js, test/web-platform-tests/to-upstream/.eslintrc.json, test/web-platform-tests/to-upstream/html/obsolete/requirements-for-implementations/other-elements-attributes-and-apis/window-external.html
This pull request adds some required no-op methods which are part of the 'Obsolete features' section of the HTML specification.
Specifically, `clear()`, `captureEvents()` and `releaseEvents()` on document:
https://html.spec.whatwg.org/multipage/obsolete.html#dom-document-clear
And the latter two again on window:
https://html.spec.whatwg.org/multipage/obsolete.html#dom-window-captureevents
It also implements the [`External`](https://html.spec.whatwg.org/multipage/obsolete.html#dom-external) interface used for `window.external`, no-ops for the two SearchProvider methods that go with it and a to-upstream test for this.
Finally, I took the opportunity to remove some unimplemented IDL for the alternative stylesheets API which has been …
=> Add several obsolete no-op methods

test/web-platform-tests/index.js
I gave the disabled tests another spin considering recent changes. Thanks to the hard work of @TimothyGu, it seems HTMLCollection is wonky no more :-)
=> Enable document.forms test

lib/jsdom/living/nodes/HTMLTableElement-impl.js, lib/jsdom/living/nodes/HTMLTableElement.idl, test/web-platform-tests/index.js
HTMLTableElement's [tFoot](https://html.spec.whatwg.org/#dom-table-tfoot-2) and [tHead](https://html.spec.whatwg.org/#dom-table-thead-2) properties only have getters at the moment. This causes failures in [the-table-element/tFoot.html](https://github.com/w3c/web-platform-tests/blob/master/html/semantics/tabular-data/the-table-element/tFoot.html) and [the-table-element/tHead.html](https://github.com/w3c/web-platform-tests/blob/master/html/semantics/tabular-data/the-table-element/tHead.html).
=> HTMLTableElement tFoot/tHead missing setter

test/old-api/env.js, test/old-api/inside-worker-smoke-tests.js, test/to-port-to-wpts/current-script.js, test/to-port-to-wpts/misc2.js
Our tests relied on the fact that scripts ran when the whole document
was loaded into memory. This is not guaranteed in a streaming parser.
Let's not test jsdom implementation specific behaviour if it goes
against expected web platform behaviour.
=> Fix wrong script tests

lib/jsdom/living/nodes/HTMLLabelElement-impl.js, test/web-platform-tests/to-upstream.js, test/web-platform-tests/to-upstream/html/semantics/forms/the-label-element/disabled-labeled-control.html
Fixes #1925 
I opted to test the specific incorrect behavior I discovered (where the labeled control is a checkbox). Alternatively, I could simply test that the "click" event is never dispatched. Let me know if that more generic test would be preferable.
=> Do not trigger click on a disabled labeled control

lib/jsdom/living/helpers/create-event-accessor.js, lib/jsdom/living/nodes/GlobalEventHandlers-impl.js, test/web-platform-tests/index.js
We set the raw event body to null if compiling the source fails,
which previously led to us re-appending when we set another inline
attribute.
Fixes #1948.
=> Only append inline handlers for an element once

test/web-platform-tests/index.js
Sadly jsdom/webidl2js#67 is a thing so our anchor stringifier doesn't actually work and we had no other tests for it...
=> Enable more wpt tests from table and anchor categories

lib/jsdom/living/nodes/Document-impl.js, lib/jsdom/living/register-elements.js, test/web-platform-tests/index.js
This pull requests assigns the HTMLElement interface to the following elements:
`acronym`
`basefont`
`big`
`center`
`nobr`
`noembed`
`noframes`
`noscript`
`plaintext`
`rb`
`rtc`
`strike`
`sub`
`summary`
`sup`
`tt`
...as well as the HTMLPreElement interface to `listing` and `xmp` as [mentioned](https://html.spec.whatwg.org/multipage/dom.html#elements-in-the-dom%3Aelement-interface) in the specification.
I have included a test which looks at the interfaces being used, but further work will be needed before it fully passes as noted in the associated comment. I've also simplified the code used to initialise the elements, moving the list of HTMLElements to register-elements.js.
=> Use correct interfaces for many elements

lib/jsdom/living/nodes/HTMLDetailsElement-impl.js, lib/jsdom/living/nodes/HTMLDetailsElement.idl, lib/jsdom/living/nodes/HTMLMarqueeElement-impl.js, lib/jsdom/living/nodes/HTMLMarqueeElement.idl, lib/jsdom/living/nodes/HTMLPictureElement-impl.js, lib/jsdom/living/nodes/HTMLPictureElement.idl, lib/jsdom/living/register-elements.js, test/web-platform-tests/index.js
This pull request adds implementations for the `<details>` and `<picture>` elements, as well as a stub for `<marquee>`.
The `<details>` "toggle" event is implemented, though it is missing one step involving a [task queue](https://html.spec.whatwg.org/#details-notification-task-steps) which I wasn't entirely sure how to approach. It uses the Event constructor, as it seems to be needed to set isTrusted.
=> Implement the details, picture and marquee elements

lib/jsdom/living/xhr-sync-worker.js, lib/jsdom/living/xmlhttprequest.js
I figured that rather than using JSON.parse()'s reviver function, it might be more efficient to let JSON.parse() do its thing and modify the resulting object afterwards.
This seems to cut the time spent parsing the result from the other process from an average of 650ms to 60ms. It should help with https://github.com/tmpvar/jsdom/issues/1833, and might allow us to enable some timeout-tests :-)
=> Speed up sync XHR result parsing

lib/jsdom/browser/Window.js, lib/jsdom/living/events/CompositionEvent-impl.js, lib/jsdom/living/events/CompositionEvent.webidl, lib/jsdom/living/events/FocusEvent-impl.js, lib/jsdom/living/events/KeyboardEvent-impl.js, lib/jsdom/living/events/KeyboardEvent.webidl, lib/jsdom/living/events/MouseEvent.webidl, lib/jsdom/living/events/UIEvent-impl.js, lib/jsdom/living/events/UIEvent.webidl, lib/jsdom/living/events/WheelEvent-impl.js, lib/jsdom/living/events/WheelEvent.webidl, lib/jsdom/living/index.js, test/web-platform-tests/index.js
This is rebased on https://github.com/tmpvar/jsdom/pull/1953 to avoid conflict.
Fixes #1959.
=> Fix FocusEventImpl inheritance

lib/jsdom/living/nodes/HTMLScriptElement-impl.js, test/api/options-run-scripts.js
This makes debugging WPT drastically easier. With the new API, this requires `includeNodeLocations` option to work.
Column is not tracked since it works a bit differently:
```
> vm.runInContext('throw new Error()', ctx, { columnOffset: 4 })
evalmachine.<anonymous>:1
throw new Error()
^
Error
at evalmachine.<anonymous>:1:11
```
=> Use correct line number for <script> if possible

lib/jsdom/living/navigator/Navigator.webidl
I was trying to install https://github.com/tmpvar/jsdom/pull/1994 from git and ran into this kind of puzzling error:
```
% npm install
> jsdom@11.3.0 prepare /Users/andrew/projects/jsdom
> yarn convert-idl
yarn convert-idl v0.23.4
$ node ./scripts/webidl/convert 
WebIDLParseError {
message: 'The name "NavigatorCookies" of type "interface" is already seen',
line: 44,
input: ' {\n  readonly ',
tokens: 
[ { type: 'whitespace', value: ' ' },
{ type: 'other', value: '{' },
{ type: 'whitespace', value: '\n  ' },
{ type: 'identifier', value: 'readonly' },
{ type: 'whitespace', value: ' ' } ] }
error Command failed with exit code 1.
```
Some how there were two copies of that... I'm surprised I'm the only one to run into this though.
=> Remove duplicate NavigatorCookies

lib/old-api.js
This happens when the input string contains a NUL character.
=> Make tests pass on Node.js 9.x

.travis.yml, Contributing.md
Small bit of followup after the changes in https://github.com/tmpvar/jsdom/pull/1999.
Removes two remaining `yarn run`'s, as well as the double dashes which are not needed in commands when using Yarn.
=> Yarn followup

lib/jsdom/browser/htmltodom.js, test/web-platform-tests/to-upstream/domparsing/DOMParser-xml-character-entities.html
To be consistent with browser implementations, `parseFromString` should not parse HTML character entities in XML documents.
node sax already provides a `strictEntities` option. This commit enables this option, ensuring only predefined XML character entities (`&amp;`, `&apos;`, `&gt;`, `&lt;`, and `&quot;`) are parsed.
See: https://github.com/isaacs/sax-js/tree/master#arguments
See: https://www.w3.org/TR/REC-xml/#sec-predefined-ent
---
Chrome 61:
=> Correct DOMParser parsing of HTML entities in XML

README.md, lib/api.js, lib/jsdom/browser/Window.js, lib/jsdom/living/nodes/Document-impl.js, lib/old-api.js, package.json, test/api/options.js, test/web-platform-tests/run-single-wpt.js, test/web-platform-tests/to-run.yaml, test/web-platform-tests/to-upstream/html/webappapis/animation-frames/no-interference-timers.html, yarn.lock
~This seems deceptively straightforward...~ It was :P
I'm unsure how to test this. The readme in `test/api/README.md` says that the web-platform tests should cover this. Am I supposed to pull in some extra tests?
My current "test" is running this script:
```js
const { JSDOM } = require('./');
const { window } = new JSDOM();
window.requestAnimationFrame(console.log);
const id = window.requestAnimationFrame(console.log);
window.cancelAnimationFrame(id);
```
It outputs e.g. `1752.195617`.
We can add https://npmjs.com/raf if a battel-tested implementation is wanted.
Fixes #1963
EDIT: Ah, figured it out, I think. Activated some more tests. One of them fails, though (commented it out), anything I can do about that?
=> Add {request,cancel}AnimationFrame

lib/jsdom/browser/htmltodom.js, test/web-platform-tests/to-upstream/domparsing/DOMParser-parseFromString-xml-CDATA.html
Fixes #1593
We're using JSDOM for unit testing a content player that (ab)uses XML by embedding HTML within CDATA tags. Unfortunately all CDATA sections are ignored by JSDOM's implementation of `DOMParser`. Were we designing an XML-based content format today, we would probably opt for XML namespacing or escaping HTML.
=> Teach DOMParser.parseFromString to parse XML CDATA

Contributing.md
Changed `Attr.idl` -> `Attr.webidl`
=> Editorial: Fix broken link to Attr.webidl in Contributing.md

lib/jsdom/living/attributes.js, lib/jsdom/living/attributes/Attr-impl.js, lib/jsdom/living/attributes/NamedNodeMap-impl.js, lib/jsdom/living/attributes/NamedNodeMap.webidl, lib/jsdom/living/index.js, lib/jsdom/living/nodes/Element-impl.js
This also switches the ownership of "attribute list" and the associated cache to Element, which is a more literal reading of the spec and simplifies things here in jsdom.
=> Convert NamedNodeMap to IDL

package.json
It can be helpful to reset the Web Platform Tests submodule when switching between older branches or after temporarily modifying test files. While some git commands seem like they would handle this, removing the folder and reinitializing it appears to be the only foolproof way of restoring the state for all situations, in my experience.
This pull request adds a small `reset-wpt` script to make this a quick and discoverable process. It also moves the submodule initialization command into its own `init-wpt` script so that it can be used by both this and the `pretest` script.
=> Add a reset-wpt script to package.json

test/web-platform-tests/run-single-wpt.js, test/web-platform-tests/run-tuwpts.js, test/web-platform-tests/run-wpts.js, test/web-platform-tests/start-wpt-server.js
This is an attempt to address recent flaky builds, which we think might be caused because the server is starting in the middle of a JSDOM API test, causing a timeout for the currently-running JSDOM API test.
The previous design started booting the server the first time it was needed, and made all tests wait for the server-creation promise before commencing their actual logic. Now, server-creation runs in a before() block.
In the process, it removes the fallback to w3c-test.org, as that configuration isn't tested and generally can cause issues.
=> Start web platform tests server before tests run

test/web-platform-tests/to-run.yaml
This test originally got enabled in https://github.com/tmpvar/jsdom/pull/2023, but was seemingly re-disabled during a rebase of that pull request.
=> Enable 'option-text-setter' test which passes

.travis.yml
Since we continue to see spurious failures on Travis for reasons which may be out of our control, it could help to give them a retry.
=> Give failing tests on Travis a second chance

lib/jsdom/browser/Window.js, lib/jsdom/living/index.js, lib/jsdom/living/window/BarProp-impl.js, lib/jsdom/living/window/BarProp.webidl, lib/jsdom/living/window/Screen-impl.js, lib/jsdom/living/window/Screen.webidl, test/web-platform-tests/to-run.yaml
These are a collection of changes I made while exploring the accuracy of our `window` implementation.
* Implement the `BarProp` interface and the `window` attributes that use it.
* Implement the `Screen` interface used for `window.screen`, which was previously just an object with two properties instead of the six attributes it actually contains. Tested in `cssom-view-window-screen-interface.html` and `Screen-pixelDepth-Screen-colorDepth001.html`.
* Implement `window.devicePixelRatio` with the default value `1`.
* Implement `window.status` which exists for historical reasons.
* Expose the `External` interface.
=> Various additions and corrections for window

lib/jsdom/browser/Window.js
This pull request removes some non-standard properties on `window` - `scrollLeft`, `scrollTop` and the `createPopup()` stub.
I also added a note for the `screenLeft` and `screenTop` properties which are not standardized at the moment, but implemented in all browsers except Firefox and therefore [likely to be added](https://github.com/w3c/csswg-drafts/issues/1091) to CSSOM View in the future.
In theory this could be considered a breaking change along the lines of https://github.com/tmpvar/jsdom/pull/2069, though it'd be surprising if someone depends on these non-standard dummy/stub properties being present.
=> Remove some non-standard parts of window

lib/jsdom/living/domparsing/DOMParser.webidl, lib/jsdom/living/events/Event.webidl, lib/jsdom/living/events/EventTarget.webidl, lib/jsdom/living/events/FocusEvent.webidl, lib/jsdom/living/events/HashChangeEvent.webidl, lib/jsdom/living/events/KeyboardEvent.webidl, lib/jsdom/living/events/MessageEvent.webidl, lib/jsdom/living/events/MouseEvent.webidl, lib/jsdom/living/events/PopStateEvent.webidl, lib/jsdom/living/events/TouchEvent.webidl, lib/jsdom/living/events/UIEvent.webidl, lib/jsdom/living/file-api/Blob.webidl, lib/jsdom/living/file-api/File.webidl, lib/jsdom/living/file-api/FileList.webidl, lib/jsdom/living/file-api/FileReader.webidl, lib/jsdom/living/navigator/Navigator.webidl, lib/jsdom/living/window/External.webidl, lib/jsdom/living/window/History.webidl, lib/jsdom/living/window/Location.webidl
Updates for the remaining Web IDL after https://github.com/tmpvar/jsdom/pull/2053 handles the nodes/ directory. An exception is `Attr.webidl`, which I've left unchanged as it depends on the work from https://github.com/tmpvar/jsdom/pull/1822.
=> Update all the Web IDL - Part Two

package.json, yarn.lock
This version does not have TypeScript typings for Node.js as a dependency.
=> Upgrade parse5 to v4.0.0

lib/jsdom/browser/Window.js, lib/jsdom/living/hr-time/DOMHighResTimeStamp.webidl, lib/jsdom/living/hr-time/Performance-impl.js, lib/jsdom/living/hr-time/Performance.webidl, lib/jsdom/living/index.js, package.json, scripts/webidl/convert.js, test/web-platform-tests/to-run.yaml, test/web-platform-tests/to-upstream/hr-time/timeOrigin-dont-upstream.html, yarn.lock
This pull request implements the `Performance` interface and `window.performance` as defined by the [High Resolution Time](https://w3c.github.io/hr-time/#the-performance-interface) specification, with the exception of the default toJSON operation as it is not supported by webidl2js yet.
I use `Date.now()` to obtain the "time origin timestamp" as I am not aware of another way to obtain a reference to an absolute time without native code.
This resolves https://github.com/tmpvar/jsdom/issues/1510.
=> Implement window.performance

lib/jsdom/living/helpers/stylesheets.js, lib/jsdom/living/nodes/HTMLStyleElement-impl.js, test/web-platform-tests/to-run.yaml, test/web-platform-tests/to-upstream/html/semantics/document-metadata/the-style-element/sheet-with-disconnected-style.html, test/web-platform-tests/to-upstream/html/semantics/document-metadata/the-style-element/sheet-with-empty-style.html
In particular, fixes #2122, where it was discovered that as of 8c84ebf3b7f3420b6e6cc68612ed3e0b9c1f4455 we wrongly made the sheet null for empty `<style>` elements.
There are a lot more issues with this area of the codebase, as discovered in https://github.com/tmpvar/jsdom/issues/2122#issuecomment-359992111. But we'll tackle them incrementally in #2124. This fixes one of them, about disconnected sheets, but leaves the ones having to do with `<link>` and @import and parsing alone for now.
=> Fix <style>'s sheet property

lib/jsdom/browser/htmltodom.js, lib/jsdom/browser/parse5-adapter-parsing.js, lib/jsdom/living/nodes/Document-impl.js, lib/jsdom/living/nodes/HTMLScriptElement-impl.js, lib/jsdom/living/nodes/HTMLStyleElement-impl.js, package.json, test/api/jsdom-errors.js, test/api/methods.js, test/index.js, test/to-port-to-wpts/on-error.js, test/web-platform-tests/to-upstream/html/semantics/document-metadata/the-style-element/non-parser-style.html, test/web-platform-tests/to-upstream/html/semantics/document-metadata/the-style-element/with-spaces.html, yarn.lock
This replaces our previous hacky <script>-only close tag detection, which only worked in non-empty <script> cases, with a more general hacky version that works for all elements, including empty elements, by monkeypatching parse5. (Eventually https://github.com/inikulin/parse5/issues/237 should give us a better solution, but for now we lock our parse5 version and monkeypatch it.)
In particular, this allows us to not parse stylesheets before their close tag is encountered, which fixes #2123 and fixes #2131.
=> Fix <style> and <script> parsing to wait for their close tag

lib/jsdom/living/nodes/HTMLImageElement-impl.js, test/to-port-to-wpts/htmlimageelement.js, test/web-platform-tests/run-single-wpt.js, test/web-platform-tests/to-upstream/html/semantics/embedded-content/the-img-element/remove-attribute-src.html
This change should fix exception raised while removing src attribute from HTMLImageElement (https://github.com/jsdom/jsdom/issues/2150)
=> Fix HTMLImageElement removeAttribute for src

lib/jsdom/browser/Window.js, package.json
Shouldn't make a practical difference as `w3c-hr-time` uses `browser-process-hrtime` (thus no change in lockfile), but it simplifies things a tiny bit.
=> Implement requestAnimationFrame using performance.now

README.md
The only trace I could find is in [this issue](https://github.com/jsdom/jsdom/issues/1924). 
Ideally jsdom could log something to the console if the it sees a script element with an external script without the `resources: "usable"` option.
=> Document how to execute external scripts

lib/jsdom/living/nodes/Document-impl.js, lib/jsdom/living/nodes/DocumentFragment-impl.js, lib/jsdom/living/nodes/NonElementParentNode-impl.js, lib/jsdom/living/nodes/NonElementParentNode.webidl, test/web-platform-tests/to-upstream/dom/nodes/DocumentFragment-getElementById.html
Based on a patch by @Zirro from IRC, with my own tests added. However, this does *not* work, because the functions in Element-impl.js that update the `_ids` collection do not care about DocumentFragment containers.
I'm unsure how to proceed. I guess one route is to have totally separate implementations of getElementById for Document and DocumentFragment, with the DocumentFragment version doing a whole traversal. That seems relatively easy. Alternately we could try to develop some kind of caching system, and a notation of "root" i.e. furthest ancestor.
Thoughts welcome.
=> Add DocumentFragment.prototype.getElementById

lib/jsdom/living/node.js, lib/jsdom/living/nodes/DOMImplementation-impl.js, test/web-platform-tests/to-upstream/dom/nodes/Node-cloneNode-document-with-doctype.html
Previously it would not clone all pieces of state, and sometimes would add an extra doctype.
Also removes some unnecessary-in-a-webidl2js-world argument conversion code from DOMImplementation's createDocument().
Closes #2191.
=> Fix cloning of Documents

lib/jsdom/living/nodes/HTMLCanvasElement-impl.js
Just a single line change replacing 
`Math.min(0, Math.max(1, qualityArgument)) * 100 
`
with
`Math.max(0, Math.min(1, qualityArgument)) * 100`
=> Fixed a line in toBlob() where quality was always taken to be 0

.travis.yml, lib/jsdom/living/events/Event-impl.js, lib/jsdom/living/events/Event.webidl, test/web-platform-tests/start-wpt-server.js, test/web-platform-tests/to-run.yaml, test/web-platform-tests/tuwpt-config.json, test/web-platform-tests/wpt-config.json
This includes updates to the configuration, accounting for changes upstream. I've also added support for Event's `srcElement` (an alias of `target`) and `returnValue`.
For the latter, the last test in this file is still failing: https://github.com/w3c/web-platform-tests/blob/master/dom/events/Event-returnValue.html#L55
The test seems incorrect to me as it relies on the `cancelable` flag being true by default for an event created with `new Event("foo")`, but I've left it enabled so that we can verify whether this is the case before merging.
=> Roll Web Platform Tests

test/old-api/env.js, test/util.js
Follow-up to https://github.com/jsdom/jsdom/pull/2216. Turns out that more than one test relied on the reddit.html file.
=> Fix browser-only test

package.json, test/web-platform-tests/to-run.yaml, yarn.lock
It includes a fix to make the href setter propagate changes to `URL.searchParams`, allowing the `url/url-constructor.html` test to pass.
=> Upgrade whatwg-url to version 6.4.1

lib/jsdom/living/helpers/form-controls.js, lib/jsdom/living/helpers/traversal.js, lib/jsdom/living/nodes/HTMLButtonElement-impl.js, lib/jsdom/living/nodes/HTMLButtonElement.webidl, lib/jsdom/living/nodes/HTMLInputElement-impl.js, lib/jsdom/living/nodes/HTMLInputElement.webidl, lib/jsdom/living/nodes/HTMLLabelElement-impl.js, lib/jsdom/living/nodes/HTMLLabelElement.webidl, lib/jsdom/living/nodes/HTMLMeterElement-impl.js, lib/jsdom/living/nodes/HTMLMeterElement.webidl, lib/jsdom/living/nodes/HTMLOutputElement-impl.js, lib/jsdom/living/nodes/HTMLOutputElement.webidl, lib/jsdom/living/nodes/HTMLProgressElement-impl.js, lib/jsdom/living/nodes/HTMLProgressElement.webidl, lib/jsdom/living/nodes/HTMLSelectElement-impl.js, lib/jsdom/living/nodes/HTMLSelectElement.webidl, lib/jsdom/living/nodes/HTMLTextAreaElement-impl.js, lib/jsdom/living/nodes/HTMLTextAreaElement.webidl, test/web-platform-tests/to-run.yaml, test/web-platform-tests/to-upstream/html/semantics/forms/the-label-element/label-attributes-dont-upstream.html, test/web-platform-tests/to-upstream/html/semantics/forms/the-label-element/label-control-attribute.html
Adds support for the HTMLLabelElement.control and *.labels properties. (jsdom/jsdom#2175)
Adds labels property support for:
- button
- input (if the type attribute is not in the Hidden state)
- meter
- output
- progress
- select
- textarea
Activated tests:
- button-labels.html
- input-labels.html
- labelable-elements.html
Added tests:
- label-attributes-dont-upstream.html (copy from wpt without 2 failing tests.)
=> Add support for HTMLLabelElement.control

test/web-platform-tests/run-single-wpt.js, test/web-platform-tests/to-run.yaml
Figured I'd finally see if I could find the cause of this issue. Turns out that a path that was meant to be rewritten by the WPT server got overridden and used by the `/resources/`-condition here before that happened. The fix performs the same replacement as the [WPT server](https://github.com/w3c/web-platform-tests/blob/master/tools/serve/serve.py#L271).
This change alone hasn't made any tests pass since most of them also depend on `fetch()`, but I suppose it'll come in handy when we eventually do support it - assuming the rewrite is still in use at that point.
=> Fix 'WebIDL2 is not defined'-error in tests

lib/jsdom/living/helpers/form-controls.js, lib/jsdom/living/helpers/traversal.js, lib/jsdom/living/nodes/HTMLLabelElement-impl.js, lib/jsdom/living/nodes/Node-impl.js, lib/jsdom/living/nodes/Node.webidl, test/web-platform-tests/to-run.yaml
Spec: https://dom.spec.whatwg.org/#dom-node-getrootnode
https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode
> composed: A Boolean that indicates whether the shadow root should be returned (false, the default), or a root node beyond shadow root (true).
Because jsdom doesn't support Shadow DOM, it should be safe to ignore the composed option.
wpt test: rootNode.html
=> Implementation of Node.getRootNode

lib/jsdom/living/nodes/HTMLSourceElement-impl.js
The getter for the `srcset` attribute on `<source>` elements would attempt to return the value of `cite` attributes instead. Thanks to @Treora for noticing and [letting us know](https://github.com/jsdom/jsdom/commit/d4d1cfea86d894ed665911dca0b39b626df56c0b#r29018531) about this.
=> Fix HTMLSourceElement.srcset getter

lib/jsdom/living/nodes/Node-impl.js, test/web-platform-tests/to-upstream/dom/nodes/Node-normalize.html
The normalize method of Node should only modify nodes that have ``node.nodeType === Node.TEXT_NODE``. The previous code was modifying all kinds of nodes that should not have been modified. This commit fixes the problem.
I've put a test in `to-upstream` that tests the change but the test has already been submitted to upstream in [this PR](https://github.com/w3c/web-platform-tests/pull/10735).
=> Fix normalize to avoid touching non-Text nodes.

package.json, yarn.lock
Greetings. I use jsdom a lot in testing applications with jest. We have run into issues when our application code cannot get style values that are not implemented in cssstyle. Like the css3 unit `rem`, for example.
```js
const jsdom = require('jsdom');
const assert = require('assert');
const { JSDOM } = jsdom;
const doc = new JSDOM(`
<p style="width:10px" id="px">Hello world</p>
<p style="width:10rem" id="rem">Hello world</p>
`).window.document;
assert.strictEqual(doc.querySelector('#px').style.width, '10px'); // ok
assert.strictEqual(doc.querySelector('#rem').style.width, '10rem');
// AssertionError [ERR_ASSERTION]: '' === '10rem'
```
I have taken ownership of the cssstyle github project and bumped it to 0.3.1 with a few PRs that had been open for awhile: …
=> Upgrade cssstyle >= 0.3.1 < 0.4.0

lib/jsdom/living/helpers/selectors.js, lib/jsdom/living/nodes/Element-impl.js, lib/jsdom/living/nodes/ParentNode-impl.js, package.json, yarn.lock
This replaces nwmatcher with [nwsapi](https://github.com/dperini/nwsapi) which resolves many known issues, supports several new selectors and is significantly faster.
Although a beta version of nwsapi is currently used, all tests should pass and this pull request is ready for review. A stable version of nwsapi is expected to be published later this week.
=> Use NWSAPI

lib/old-api.js, test/web-platform-tests/run-wpts.js, test/web-platform-tests/to-run.yaml
With this, we should be able to merge https://github.com/jsdom/jsdom/pull/2225 and begin testing in Node.js v10. Fixes: https://github.com/jsdom/jsdom/issues/2211
The new failure reason is hopefully a one-off, but means that we can continue testing `Blob-slice.html` in other versions of Node.
=> Fix issues with Node.js v10

test/web-platform-tests/to-run.yaml
While they're currently disabled with the `fail` reason, these tests also appear to end in a timeout for testharness.
=> Use `timeout` for all tests where it applies

lib/jsdom/browser/Window.js, lib/jsdom/living/events/StorageEvent-impl.js, lib/jsdom/living/events/StorageEvent.webidl, lib/jsdom/living/index.js, lib/jsdom/living/nodes/HTMLFrameElement-impl.js, lib/jsdom/living/webstorage/Storage-impl.js, lib/jsdom/living/webstorage/Storage.webidl, scripts/webidl/convert.js, test/web-platform-tests/run-wpts.js, test/web-platform-tests/to-run.yaml
This is a work-in-progress implementation of the `Storage` interface, along with `localStorage`, `sessionStorage` and the `storageEvent`. It resolves https://github.com/tmpvar/jsdom/issues/1137.
All the tests for storing data are currently passing, but some of the event tests will require further work. I welcome feedback at this stage, but keep in mind that this is not yet complete.
(Also, thank you @TimothyGu for making this a breeze to implement through all your improvements to webidl2js!)
=> Implement Web storage - localStorage, sessionStorage, StorageEvent

package.json, yarn.lock
This release includes jsakas/CSSStyleDeclaration#52, which at long last fixes the `v.toLowerCase is not a function` error when setting `border-spacing` to `0` or `'0'`.
Also, as of this release, cssstyle will follow semver: jsakas/CSSStyleDeclaration#59
=> Upgrades cssstyle dependency to ^1.0.0

Changelog.md
I noticed a few minor issues in the changelog while I was looking through the recent entries - a couple of duplicated letters and the mention of `imgEl.srcset` rather than `sourceEl.srcset` where [the fix](https://github.com/jsdom/jsdom/pull/2234) was made.
=> Fix a few entries in the changelog

lib/jsdom/living/form-data-symbols.js
It seems like this file no longer is required as of https://github.com/jsdom/jsdom/commit/63f8010cba0a3ac4be9355e5a190aada9da97d2e.
=> Remove unused form-data-symbols.js file

README.md, lib/api.js, lib/jsdom/browser/Window.js, lib/jsdom/living/webstorage/Storage-impl.js, lib/old-api.js, test/api/options.js, test/web-platform-tests/run-single-wpt.js
Fixes the problem noticed by @fstoerkle in https://github.com/jsdom/jsdom/commit/3afbc0feb7b2b4ac4c84530ea6af90e1f79a88ee#r29395675. Thanks!
It's probably not appropriate to write a WPT for this given that the quota merely is a recommendation.
=> Add the `storageQuota` option

.gitignore, package.json
This speeds up linting by ~10 seconds on my machine. The option is not enabled in ESLint by default since it interferes with plugins that require looking at dependent files to produce a result, but that's not a problem with the plugins we're using here as far as I can tell.
=> Use ESLint's cache option

lib/jsdom/living/helpers/dates-and-times.js, package.json, yarn.lock
Since it looks like we'll require Node.js v8 with the next major release, we can use `String.prototype.padStart()` and remove a dependency.
=> Use String.prototype.padStart()

lib/jsdom/browser/Window.js, test/web-platform-tests/to-upstream/html/browsers/the-window-object/window-properties-dont-upstream.html
This property was previously missing because it exposed a bug in the `vm` module on Node.js v6 which appeared in a few XHR tests. The bug has been fixed in later versions.
Spec: https://html.spec.whatwg.org/multipage/#dom-window-status
=> Add window.status

lib/api.js, lib/jsdom/browser/htmltodom.js, lib/jsdom/browser/parse5-adapter-serialization.js, lib/jsdom/living/nodes/HTMLScriptElement-impl.js, package.json, test/api/methods.js, test/api/options-run-scripts.js, yarn.lock
[Version 5.0.0](https://github.com/inikulin/parse5/blob/master/docs/version-history.md) of parse5 was just released and it implements the `scriptingEnabled` flag which may allow us to fix issues https://github.com/jsdom/jsdom/issues/1611 and https://github.com/jsdom/jsdom/issues/1802. This pull request only includes the changes necessary for the upgrade at the moment, though.
It also includes some breaking changes to the location info, but I'm happy to report that the only fix required because of the temporary monkey-patch was the replacement of underscores with dashes in a filename.
=> Use parse5 v5.0.0

README.md, lib/jsdom/browser/resources/resource-loader.js, test/api/from-url.js, test/api/resources.js
Implements the suggested solution to https://github.com/jsdom/jsdom/issues/2294 when `process.platform` is unavailable, resulting in the User-Agent string:
`Mozilla/5.0 (unknown OS) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.12.0`.
I'm not convinced that this is the long-term solution we want for the UA string given how different the values are from those in browsers (`win32` vs `Windows NT 10.0; Win64; x64`), but it solves the `undefined`-problem at least.
Fixes #2294.
=> Provide `process.platform` fallback for User-Agent string

Changelog.md, README.md, lib/jsdom/living/nodes/ParentNode-impl.js, package.json
For these selector methods, before bfb08434f540491591aace17b302816f146dd4ef they were memoized, which kept them outside the class. Now we can just put them in the class, like normal methods.
Will merge once CI is happy.
=> Minor code and README cleanups; note Node.js version requirement

lib/jsdom/living/nodes/HTMLFieldSetElement-impl.js, lib/jsdom/living/nodes/HTMLFieldSetElement.webidl, test/web-platform-tests/to-run.yaml, test/web-platform-tests/to-upstream/html/semantics/forms/the-fieldset-element/HTMLFieldSetElement-dont-upstream.html
Specifically, HTMLFieldSetElement's `elements` and `type` getters. I've also added a dont-upstream test since the original version depends on HTMLFormElement's named properties, replacing them with `querySelector()` instead.
=> Implement remaining properties of the `fieldset` element

package.json, yarn.lock
Closes #2281 
We fixed this upstream in the `cssstyle` package in this pull request: https://github.com/jsakas/CSSStyleDeclaration/pull/61 and the fix was published in version 1.1.0, so just by upgrading the above issue should be resolved.
Here's a diff from version 1.0.0 to 1.1.1 so that the impact from the upgrade can be better evaluated: https://github.com/jsakas/CSSStyleDeclaration/compare/v1.0.0...v1.1.1
Let me know if anything else should be done in this PR to accept this change!
=> Upgrade `cssstyle` dependency from ^1.0.0 to ^1.1.1

README.md, lib/api.js, test/api/methods.js
In order to prevent scripts from potentially running forever, it'd be great to be able to pass a `timeout` to it.
Docs: https://nodejs.org/api/vm.html#vm_script_runincontext_contextifiedsandbox_options
=> fix: pass vm scrip options through

.eslintignore, package.json
I occasionally see pull requests where linting errors from `to-upstream` don't appear on the initial CI run, as the second linting command only runs if there's no error from the first.
Using `;` will ensure that errors in both locations show up right away.
=> Lint scripts in HTML and JS files during same run

lib/jsdom/utils.js
In some environments, neither `canvas`, nor `canvas-prebuilt` will be installed - as it is an optional dependency, we will just ignore their absence, however when one or both of them are installed, there is a chance that loading them fails, as they are depending on native bindings.
For example when building a docker image that runs `sid`, `libpng12-0` is not available, which means that loading (requiring) canvas-prebuilt fails, due to:
> `error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory`
It took me quite a while to figure out why canvas-prebuilt worked outside the docker container, but not inside, even though both systems were linux.
The way the try/catch is currently set up means that loading errors are swallowed. The change …
=> canvas/canvas-prebuilt: show error when module is available but fails to load

lib/jsdom/living/nodes/HTMLAnchorElement-impl.js, lib/jsdom/living/nodes/HTMLAnchorElement.webidl, lib/jsdom/living/nodes/HTMLAreaElement-impl.js, lib/jsdom/living/nodes/HTMLAreaElement.webidl, lib/jsdom/living/nodes/HTMLLinkElement-impl.js, lib/jsdom/living/nodes/HTMLLinkElement.webidl, test/web-platform-tests/to-run.yaml, test/web-platform-tests/to-upstream/dom/lists/DOMTokenList-coverage-for-attributes-dont-upstream.html
`<link>` elements have a limited set of tokens. In our case, only `stylesheet` is supported for now.
I've added a dont-upstream version of a test which checks all DOMTokenList-based properties, with the ones we don't yet support disabled.
=> Support `relList` attribute on <a>, <area> and <link> elements

test/web-platform-tests/to-run.yaml
Resolves a conflict where the roll in https://github.com/jsdom/jsdom/pull/2380 added two failing <link> tests that didn't get disabled in https://github.com/jsdom/jsdom/pull/2405 since they were merged at the same time.
=> Disable two recently added <link> tests

benchmark/html/index.js, benchmark/html/parsing.js, benchmark/index.js, lib/jsdom/living/nodes/CharacterData-impl.js
While testing various solutions for the performance regression described in https://github.com/jsdom/jsdom/issues/2350 and https://github.com/jsdom/jsdom/issues/2416, I came across this optimisation.
As it's parsing, parse5 feeds us a new chunk of text when it encounters a whitespace character in the current text node, which we insert into the existing text through CharacterData's `replaceData()` method with the help of `String.prototype.substring()`.
It turns out that despite being very similar in purpose, using `String.prototype.slice()` repeatedly can be significantly faster than `String.prototype.substring()` in V8 under certain conditions. The difference really adds up in the test cases supplied in https://github.com/jsdom/jsdom/issues/2350 which goes from ~3000ms to ~500ms and …
=> Improve the performance of parsing text

.travis.yml, test/api/methods.js, test/web-platform-tests/run-wpts.js, test/web-platform-tests/to-run.yaml
On Node.js v11, one test began to fail due to a changed error message. Under the assumption that testing for the specific kind of error will be helpful in the future, I've replaced it with a regex that matches both versions.
In addition, one test which had a timing issue - `event_no_duplicates.html` - started passing. Quite likely due to the changes in https://github.com/nodejs/node/pull/22842 which brings Node.js timers closer to browser behaviour. 🎉
I'm not sure if we want to start testing in v11 yet, so I've not changed `.travis.yml`.
=> Fix and run tests on Node.js v11

lib/jsdom/living/nodes/Element-impl.js, lib/jsdom/living/nodes/Element.webidl, test/web-platform-tests/to-run.yaml
This builds on the code in https://github.com/jsdom/jsdom/pull/2395, and implements the `insertAdjacentElement()` and `insertAdjacentText()` methods on `Element`.
It also includes a fix to use ASCII lowercase for the `position` argument in `insertAdjacentHTML()`.
Fixes https://github.com/jsdom/jsdom/issues/1890.
=> Implement `insertAdjacentElement()` and `insertAdjacentText()`

lib/jsdom/living/nodes/HTMLAnchorElement-impl.js, lib/jsdom/living/nodes/HTMLAreaElement-impl.js
Fixes a regression introduced through https://github.com/jsdom/jsdom/commit/064527e2cbc003debe0bc826f893519f1ceb64bc where the `style` property on `<a>` and `<area>` elements would not get updated correctly. Given how specific the issue is, I'm not sure if adding a test would make sense here.
Resolves https://github.com/jsdom/jsdom/issues/2437.
=> Fix style property on <a> and <area> elements

lib/jsdom/living/nodes/Node-impl.js, test/web-platform-tests/to-run.yaml
While the specification only references Text nodes [in this step](https://dom.spec.whatwg.org/#ref-for-concept-node-text-change-ext), it seems like the inclusion of CDATASection nodes is implied unless the term [exclusive Text node](https://dom.spec.whatwg.org/#exclusive-text-node) is used.
If that's the case there are several places in the code where we should be matching against both Text nodes and CDATASection nodes instead of just the former, though only this location seems to be covered by our current tests. I'll create an issue for the remaining cases if this is correct.
=> Run child text content change steps when inserting CDATASection node

lib/jsdom/living/helpers/traversal.js, lib/jsdom/living/nodes/HTMLFormElement-impl.js, lib/jsdom/living/nodes/Node-impl.js, test/web-platform-tests/to-upstream/dom/nodes/Node-isConnected-shadow-dom.html
Fix issue described: https://github.com/jsdom/jsdom/issues/1030#issuecomment-437083550
This is an issue that slipped in with the introduction of the [shadow DOM](https://github.com/jsdom/jsdom/pull/2347) the isConnected returns `false` if the element is part of a shadow tree. A new WPT-test needs to be added here, since no test is checking this behavior.
=> Fix Node.isConnected in the context of a Shadow Tree

lib/jsdom/living/xhr-utils.js, test/api/resources.js
Handle nonexistent file uris similar to urls instead of throwing an exception that is not caught anywhere and causes test frameworks to fail.
Details can be found in #1579
=> Fixes #1579 JSDOM throws error for nonexistent file uri

lib/jsdom/living/helpers/traversal.js, lib/jsdom/living/nodes/Document-impl.js, lib/jsdom/living/nodes/HTMLFieldSetElement-impl.js, lib/jsdom/living/nodes/HTMLFormElement-impl.js, lib/jsdom/living/nodes/HTMLTableElement-impl.js, lib/jsdom/living/nodes/HTMLTableRowElement-impl.js, lib/jsdom/living/nodes/HTMLTableSectionElement-impl.js, lib/jsdom/living/nodes/HTMLTitleElement-impl.js, lib/jsdom/living/nodes/SVGTitleElement-impl.js, lib/jsdom/living/nodes/SVGTitleElement.webidl, lib/jsdom/living/register-elements.js, test/web-platform-tests/to-run.yaml
This adds `SVGTitleElement` and support for using it in `document.title` according to the spec at https://html.spec.whatwg.org/multipage/dom.html#document.title.
As part of this I've renamed and added an optional namespace argument for the traversal helpers to make matching elements outside the HTML namespace easier.
I've also fixed the getter of `<title>`s `text` property to correctly use the child text content instead of innerHTML: https://html.spec.whatwg.org/multipage/semantics.html#dom-title-text
This currently includes the changes from https://github.com/jsdom/jsdom/pull/2434 since one of the new tests, `document.title-not-in-html-svg.html`, is fixed through this.
=> Support SVGTitleElement, fix document.title and <title>'s text property

lib/jsdom/living/nodes/DOMImplementation-impl.js
These have not been in use since https://github.com/jsdom/jsdom/pull/2279.
=> Remove unused feature methods

lib/jsdom/living/nodes/HTMLOutputElement-impl.js, lib/jsdom/living/nodes/HTMLOutputElement.webidl, test/web-platform-tests/to-run.yaml, test/web-platform-tests/to-upstream/dom/lists/DOMTokenList-coverage-for-attributes-dont-upstream.html
Two remaining fixes/features for `<output>`, which we should fully support now. I made sure to include the `super()`-call this time 😄
=> Custom validity messages and htmlFor property for <output>

lib/jsdom/living/nodes/HTMLOListElement-impl.js, lib/jsdom/living/nodes/HTMLOListElement.webidl, test/web-platform-tests/to-run.yaml
This adds the default value for `<ol>`'s start property which is returned if the content attribute does not contain a valid integer.
=> Correctly reflect <ol>'s start property with default value

lib/jsdom/living/nodes/HTMLFieldSetElement-impl.js, test/web-platform-tests/to-run.yaml
The same fix as `<output>` got in https://github.com/jsdom/jsdom/commit/ce8e8c6837c426a6add4cb6c68b47cc667e38856.
=> Support setting custom validity messages on <fieldset>

lib/jsdom/living/domparsing/DOMParser-impl.js, lib/jsdom/living/nodes/Document-impl.js, test/web-platform-tests/to-run.yaml
The [specification](https://html.spec.whatwg.org/multipage/dom.html#current-document-readiness) is not particularly detailed regarding this, but it appears like documents created by DOMParser should have the "complete" `readyState` immediately, with three out of four browsers agreeing: https://wpt.fyi/results/domparsing/xmldomparser.html
This actually changed (regressed) in https://github.com/jsdom/jsdom/pull/2279.
=> Set readyState to "complete" for documents created by DOMParser

lib/jsdom/browser/Window.js
Fixes https://github.com/jsdom/jsdom/issues/2481 by throwing a TypeError if the argument is not an Element. I also took the opportunity to do a bit of clean up and change the default stylesheet to parse lazily which saves ~8ms during initialization for situations when `window.getComputedStyle()` never gets used.
These type-related bugs are likely already covered by the larger tests which we can't enable yet due to other reasons, so I don't think we need a new specific test case for this.
=> Make getComputedStyle() throw for incorrect argument type

lib/jsdom/living/index.js, lib/jsdom/living/navigator/MimeType-impl.js, lib/jsdom/living/navigator/MimeTypeArray-impl.js, lib/jsdom/living/navigator/Navigator.webidl, lib/jsdom/living/navigator/NavigatorPlugins-impl.js, lib/jsdom/living/navigator/Plugin-impl.js, lib/jsdom/living/navigator/PluginArray-impl.js, test/web-platform-tests/to-run.yaml
These are largely no-ops since we don't actually support any plugins.
There are tests for these in https://github.com/web-platform-tests/wpt/blob/master/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator-pluginarray.html.
=> Implement navigator.plugins and navigator.mimeTypes

lib/jsdom/browser/htmltodom.js, test/web-platform-tests/to-run.yaml
The current code does not recognise custom names/root elements within short DOCTYPES (such as the case of `<!DOCTYPE foo>`), but it seems like non-`html` names are also expected to be initialized as the `name` property of DocumentType nodes.
I decided to keep the existing `HTML5_DOCTYPE` check first as a fast path and add a new regex for the presumably rare case of custom names.
=> Support DOCTYPEs with a custom name

lib/jsdom/browser/Window.js
These were indeed added to the spec in https://github.com/w3c/csswg-drafts/pull/2669.
=> Update note for screenLeft and screenTop properties on window

test/web-platform-tests/to-upstream/cssom/getComputedStyle-style-element-updates.html
Closes #2292, which was previously fixed (probably by one of 0c54ed399b7399d3ab86e8a9d59fa7ea34e060da, dbda070c9d33fb2762abedc23376757d9f8ec7d3, or f32113b6e1307832eb75d295d9da8185dd27006a) but not explicitly tested against.
=> Add regression test for dynamic <style> updates

lib/jsdom/living/helpers/focusing.js, test/web-platform-tests/to-upstream/html/editing/focus/focus-management/focus-blur.html
This regressed in https://github.com/jsdom/jsdom/pull/2463 as it changed the location where the event's `view` property was set.
Resolves https://github.com/jsdom/jsdom/issues/2499.
=> Fix element.blur() on a focused element

README.md
I think the example somehow got out of sync. Otherwise it wouldn't be clear to me why the example should work this way.
Hope it helps.
=> Fixed fragment code example in readme

lib/api.js, test/api/fragment.js
I discovered a bug, which is triggered by the test I added (f13cb62)
The next commit fixes it. I am not sure if it is the right fix. The real problem might be a bit deeper, but I am not very familiar with jsdom.
The test output without the fix is
```
1) API: JSDOM.fragment() should be possible to append to a dom node:
AssertionError: expected '<div>undefined<div>test</div></div>' to equal '<div><div>test</div></div>'
+ expected - actual
-<div>undefined<div>test</div></div>
+<div><div>test</div></div>
at it (test/api/fragment.js:71:12)
at $mochaNoSugar$runUserTestFunc (node_modules/mocha-sugar-free/lib/mocha-sugar-free.js:64:35)
at Context.$mochaNoSugar (node_modules/mocha-sugar-free/lib/mocha-sugar-free.js:267:32)
```
=> Fix bug when appending initially empty fragment to dom node

lib/jsdom/browser/Window.js, lib/jsdom/living/events/PageTransitionEvent-impl.js, lib/jsdom/living/events/PageTransitionEvent.webidl, lib/jsdom/living/index.js, lib/jsdom/living/nodes/Document-impl.js, test/web-platform-tests/to-run.yaml
Also sets the correct target for the load event - the document rather than window - through the legacy target override flag per https://html.spec.whatwg.org/multipage/parsing.html#the-end.
=> Implement PageTransitionEvent interface and pageshow event

test/web-platform-tests/run-wpts.js, test/web-platform-tests/to-run.yaml
This adds a pretest check to verify that the DIR entries in `to-run.yaml` still are current. The directories are sometimes moved or renamed between updates. I found that `progress-events` has been merged into `xhr` at this point.
=> Verify that WPT directories still exist

lib/jsdom/living/nodes/HTMLFrameElement-impl.js, test/api/options.js
This allows a child frame to expose `requestAnimationFrame`
on its Window.
Fixes https://github.com/jsdom/jsdom/issues/2538
=> fix(frame): get pretendToBeVisual opt from parent

lib/jsdom/living/nodes/HTMLAnchorElement-impl.js, lib/jsdom/living/nodes/HTMLAreaElement-impl.js, lib/jsdom/living/nodes/HTMLHyperlinkElementUtils-impl.js, lib/jsdom/living/window/navigation.js, test/web-platform-tests/to-run.yaml
A work in progress. The code related to choosing a browsing context and `noreferrer`/`noopener` may be removed as it does not have an effect on the resulting window or document at this point.
=> Add support for links to javascript: urls and fragments

lib/jsdom/living/nodes/HTMLOptionElement-impl.js, test/web-platform-tests/to-run.yaml
For reasons that are not clear to me, this [test](https://github.com/web-platform-tests/wpt/blob/master/html/semantics/forms/the-option-element/option-label-value.js) which passes in all browsers requires that the `label` and `value` attributes don't belong to a namespace. There doesn't appear to be any special instructions regarding this in the [specification](https://html.spec.whatwg.org/multipage/form-elements.html#dom-option-label).
Is this merely missing from the spec, or is it something we're actually supposed to check for all attributes?
=> Fix <option>'s label and value properties

lib/jsdom/living/nodes/Element-impl.js, test/web-platform-tests/to-upstream/html/semantics/forms/the-progress-element/serialization-regression-test.html
Various properties that reflect HTML attributes, e.g. <progress>'s value and max properties, would cause HTML serialization (e.g. via innerHTML) to break after they were set, due to a missing conversion causing jsdom to store the attribute's value as a non-string. This fixes the problem in one central location for robustness, even if it may be more per-spec to fix it all the entry points.
Fixes #2554.
---
I'm curious on collaborators thoughts on this approach. As the commit message notes, it's a tradeoff.
=> Fix HTML serialization breaking after setting certain properties

lib/jsdom/living/nodes/HTMLStyleElement-impl.js, test/web-platform-tests/to-upstream/html/semantics/document-metadata/the-style-element/no-browsing-context.html
Fixes #2553. The spec actually does not cover this; see spec issue at https://github.com/whatwg/html/issues/4547.
=> Do not processing non-browsing-context-connected <style>s

lib/api.js, test/api/fixtures/from-file/xhtml.xht, test/api/from-file.js
The [`.xht`](https://en.wikipedia.org/wiki/XHTML) file extension is a shorter form of `.xhtml` which for completeness we ought to match alongside `.xhtml` and `.xml` in the API. This could potentially be seen as a breaking change that we should save for the next major release (though it's certainly not worth making a major release over this change alone).
=> Recognize the .xht file extension

README.md, lib/api.js, test/api/encoding.js
Fixes #2495, by making the contentType option behave more like the Content-Type header. This also simplifies the code, by unifying the code paths used by the JSDOM constructor and the JSOM.fromURL() function, now that they behave similarly.
=> Allow the contentType option to override sniffed encoding

lib/jsdom/living/file-api/Blob-impl.js
=> Always use "\n" for Blob's native line endings

lib/jsdom/living/nodes/HTMLElement-impl.js, lib/jsdom/living/nodes/HTMLElement.webidl, test/web-platform-tests/to-run.yaml
Implemented based on https://html.spec.whatwg.org/multipage/dom.html#the-translate-attribute, with the current translation mode computed on access.
=> Implement the translate attribute

lib/jsdom/living/events/EventTarget-impl.js, test/to-port-to-wpts/level2/events.js, test/web-platform-tests/to-run.yaml
This is an implementation of the changes made to the event path iteration in https://github.com/whatwg/dom/pull/686, though it's currently causing many existing tests to fail. I've not yet been able to determine whether this is due to an issue with the spec or a bug in this implementation.
=> Implement changes to event path iteration

lib/jsdom/living/nodes/HTMLInputElement-impl.js, test/web-platform-tests/to-run.yaml
This closes #2494.
This will also require an update of the web platforms tests, specifically form-validation-validity-patternMismatch.html
The test change submitted against web platform tests: https://github.com/web-platform-tests/wpt/pull/16577
=> pattern should apply to the entire string when computing patternMismatch

package.json
Following the discussion in https://github.com/jsdom/jsdom/issues/2603. This may cause a warning to appear in npm during installation as it doesn't currently support optional peer dependencies.
=> Add canvas as an optional peer dependency

lib/jsdom/browser/parser/xml.js, test/api/basics.js
Previously it would say eg. `undefined:1:17: malformed comment.`
Fixed by passing in the url as the `fileName` when creating the parser.
=> Include the url of the XML document in error messages

lib/jsdom/living/nodes/HTMLInputElement-impl.js, lib/jsdom/living/nodes/HTMLOptionElement-impl.js, lib/jsdom/living/nodes/HTMLTextAreaElement-impl.js, lib/jsdom/living/xhr/FormData-impl.js, test/web-platform-tests/to-upstream/XMLHttpRequest/formdata-constructor.html
Fixes #2523
This PR enables the `FormData` constructor to handle input elements that are defined like:
```html
<input type="text" name="look-at-me" />
```
I couldn't quite see anything in the [Living Standard](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-form-data-set) that describes what should happen when the value is not defined, but the browser behaviour for this (Chrome/Firefox at least) is to return an empty string.
=> Allow FormData constructor to handle input elements without a value

lib/jsdom/living/nodes/HTMLSelectElement-impl.js
When doing get value of Select element with selectedIndex=-1, it
should return empty string "" instead of value of its first option.
Test case:
```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const html = `
<!DOCTYPE html>
<html>
<head>
<meta name="description" content="selectedIndex test">
</head>
<body>
<select id="select">
<option value="1">1</option>
<option value="2">2</option>
<option vlaue="3">3</option>
</select>
</body>
</html>
`;
const dom = new JSDOM(html);
const select = dom.window.document.getElementById("select");
select.selectedIndex = -1;
// expectation: ""
console.log(select.value); // "1"
// expectation: -1
console.log(select.selectedIndex); // 0
```
Browser playground: https://jsbin.com/numacir/3/edit?html,console,output
Repl playground: …
=> Fix getting value of Select when selectedIndex is -1

lib/jsdom/browser/Window.js, lib/jsdom/living/helpers/style-rules.js, test/web-platform-tests/to-upstream/cssom/getComputedStyle-visibility-inheritance.html, test/web-platform-tests/to-upstream/cssom/getComputedStyle-visibility-override.html
Closes #2616 
Missing behavior:
* https://drafts.csswg.org/css-cascade-4/#cascading
* https://drafts.csswg.org/css-cascade-4/#defaulting-keywords
I would recommend reviewing the first commit separately since it only includes refactoring to make the later inheritance implementation easier.
This lays the ground work for `getComputedStyle` respecting style inheritance as well as initial values. To fully implement [`getComputedStyle`](https://drafts.csswg.org/cssom/#dom-window-getcomputedstyle) we need to implement proper specificity (code comment has a remark about this) and port https://www.w3.org/TR/CSS2/propidx.html into code.
I'd like to follow-up with implementing specificity. I'm mostly interested in visibility since it affects accessibility (`display` isn't inherited anyway and …
=> feat(window): getComputedStyle inherits visibility

.eslintrc.json, lib/jsdom/living/nodes/SVGGraphicsElement.webidl, lib/jsdom/living/nodes/SVGTests.webidl, package.json, test/web-platform-tests/to-upstream/html/dom/reflection-overridden-methods.html, yarn.lock
This notably includes webidl2js's new major release which fixes #2158. A test is included. It also requires fixing our one old-style mixin.
=> Update dev dependencies

lib/jsdom/living/nodes/HTMLOrSVGElement-impl.js, test/web-platform-tests/to-upstream/html/interaction/focus-managment/focusing-focused-noop.html
Closes #2621 
Implements
> If new focus target is the currently focused area of a top-level browsing context, then return.
-- https://html.spec.whatwg.org/multipage/interaction.html#focusing-steps
=> fix: Focusing focused dispatching FocusEvent

lib/api.js, test/api/from-url.js
Since browsers don't include hash when making http requests to the
server, do the same here. parsedURL.href was including hash (fragment).
This also fixes duplicate hash as parsedURL.href was concatenated
with parsedURL.hash and passed to JSDOM constructor and that resulted
in duplicate hash in actual document.
Resolves #2696
=> Fix fromURL API to not include hash fragment in fetch request

lib/jsdom/browser/parser/xml.js, test/web-platform-tests/to-run.yaml
This PR fixes the `HTMLTemplateElement` parsing in the context of XML document by associating the elements to the right owner document.
=> Fix XML template content owner document

lib/jsdom/living/helpers/style-rules.js
`nwsapi` seems to be able to handle multiple selectors. 
Ran `yarn workspace @material-ui/core test` (on https://github.com/mui-org/material-ui/tree/a98abed2fce2fafe16f3c459d1a0de838e5736d2) 6 times with `node@v12.11.1` on Ubuntu 18.04.3 LTS.
median c3f0f2756bdbb20e235473728b562e04a67a6555: 30s
median PR: 26s
Not every test relies on `getComputedStyles` (more like 30-40% of them).
=> feat(getComputedStyles): Improve performance

lib/jsdom/living/nodes/HTMLInputElement-impl.js, test/web-platform-tests/to-upstream/html/semantics/forms/the-input-element/default-type.html
A bug was raised in https://github.com/testing-library/react-testing-library/issues/532 caused by JSDOM not defaulting invalid input types to `"text"`.
The spec states: https://html.spec.whatwg.org/multipage/input.html#attr-input-type
>The missing value default and the invalid value default are the Text state.
Hopefully I've made the right changes in the right places and the tests are sufficient.
=> Fixed issue with invalid input types not defaulting to 'text'.

lib/jsdom/browser/Window.js
- **Node.js version:** v13.1.0
- **jsdom version:** 13.2.0
```js
const jsdom=require("jsdom");
const { JSDOM }=jsdom;
var options={
url:"http://gg.com",
pretendToBeVisual:true,
includeNodeLocations: true,
resources:'usable',
runScripts:'dangerously',
beforeParse:function(window){}
}
dom=new JSDOM('<script>function test1(){ var t=setTimeout(function(){ test1() },1); }; for(var i=0;i<1000;i++) test1(); </script>',options);
// best to run with: node --inspect test.js
// the leak is obvious on chrome://inspect
```
No leak
I use jsdom to emulate http://adventure.land 's gameplay, so the emulation needs to go on as long as possible, I've been hunting a memory leak for 2 days, since the game can run on the browser for weeks, I'm pretty sure the code itself doesn't have a memory leak
I believe …
=> setTimeout leaks memory significantly

lib/jsdom/living/file-api/FileReader-impl.js, test/web-platform-tests/to-run.yaml, test/web-platform-tests/to-upstream/FileAPI/reading-data-section/filereader_readAsDataURL.html
Bug fixed, charset is undefined when call FileReader.readAsDataURL for type text blob.
I write code following.
```javascript
const blob = new jsdom.window.Blob(['Hello'], {
type: 'text/plain;charset=utf-8',
});
const fileReader = new jsdom.window.FileReader();
fileReader.addEventListener('load', () => {
// false, result is 'data:text/plain;charset=undefined,Hello'
console.log(fileReader.result === 'data:text/plain;charset=utf-8,Hello'); 
});
fileReader.readAsDataURL(blob);
```
I think result is setting blob type charset.
But, result charset is undefined.
=> Bug fixed, charset is undefined when call FileReader.readAsDataURL for type text blob.

lib/jsdom/living/nodes/HTMLImageElement-impl.js, test/web-platform-tests/run-wpts.js, test/web-platform-tests/to-run.yaml
Closes #2701. This also enables the img element tests, with new infrastructure for selectively running them only when the canvas package is installed.
=> Do not attempt to fetch images in no-BC documents

.gitignore, lib/jsdom/browser/Window.js, lib/jsdom/living/file-api/Blob-impl.js, lib/jsdom/living/file-api/FileReader-impl.js, lib/jsdom/living/helpers/binary-data.js, lib/jsdom/living/nodes/HTMLFrameElement-impl.js, lib/jsdom/living/websockets/WebSocket-impl.js, lib/jsdom/living/xmlhttprequest.js, package.json, scripts/generate-js-globals.js, test/api/options-run-scripts.js, test/api/options.js, yarn.lock
This implements one of the strategies discussed in https://github.com/jsdom/jsdom/issues/2727 for JS globals. Namely, it aliases to the Node.js globals for when runScripts is disabled, and ensures fresh copies from the VM are used when runScripts is set.
---
Some tests currently fail with this approach. So far I am debugging the FileAPI tests. Help would be appreciated though.
=> Implement uniform strategy for JS globals in the JSDOM

lib/jsdom/living/interfaces.js
Extracted&nbsp;from <https://github.com/jsdom/jsdom/pull/2744>.
This&nbsp;ensures that&nbsp;**JSDOM** won’t&nbsp;break from&nbsp;[jsdom/webidl2js#151](https://github.com/jsdom/webidl2js/pull/151).
---
review?(@domenic)
=> fix: Avoid reinstallation of already installed interfaces

lib/jsdom/living/interfaces.js
2b0dbc98bcffa738c676dc99d49d5716e5578422 was merged slightly prematurely as it contained a no-longer necessary workaround of installing Error manually before DOMException. In particular, 3a4fd6258e6b13e9cf8341ddba60a06b9b5c7b5b made it unnecessary.
---
I'll merge this if CI is happy; no serious review should be needed.
=> Remove no-longer-necessary workaround for DOMException

.travis.yml, README.md, package.json
Closes #2730.
---
It turns out that this is no longer forced if we merge #2768 instead of #2731. But, it still seems like a good idea, since we've got a lot of breaking changes coming anyway, and Node v8 is end of life.
=> Bump minimum supported Node.js version and test v12 on CI

README.md, lib/api.js, lib/jsdom/living/helpers/create-event-accessor.js, test/api/methods.js
This allows more flexibility for vm-using consumers. Closes #2731.
@SimenB please take a look and let me know what you think!
=> Replace runVMScript() with getInternalVMContext()

lib/jsdom/living/domparsing/XMLSerializer-impl.js, lib/jsdom/living/domparsing/XMLSerializer.webidl, lib/jsdom/living/domparsing/serialization.js, lib/jsdom/living/interfaces.js, lib/jsdom/living/nodes/Element-impl.js, lib/jsdom/living/nodes/ShadowRoot-impl.js, package.json, yarn.lock
This updates to the latest version of w3c-xmlserializer, which no longer contains a generated XMLSerializer class, but just a serialize function. Instead, we now wrap that package's serialize function as appropriate. This allows us to properly generate an XMLSerializer constructor per jsdom Window, in line with other recent constructor and prototype reform.
---
Note to self: do not merge until we merge and publish https://github.com/jsdom/w3c-xmlserializer/pull/21 and update the package.json and yarn.lock in this PR.
=> Update w3c-xmlserializer dependency

lib/jsdom/living/interfaces.js, package.json, yarn.lock
This uses the newest version of the whatwg-url package, which integrates with the constructor and prototype reform changes, and thus creates new URL and URLSearchParams constructors per JSDOM Window object.
The data-urls update is to synchronize with whatwg-url so that their common dependencies are deduplicated properly.
=> Update whatwg-url and data-urls dependencies

lib/jsdom/living/nodes/DocumentFragment-impl.js, test/web-platform-tests/to-upstream/dom/nodes/DocumentFragment-constructor.html
Fix DocumentFragment constructor by setting the ownerDocument associated with the current global object.
Fixes #2274.
=> Fix incorrect DocumentFragment constructor

test/api/options-run-scripts.js
The intention of this code was to skip these tests on Node v10, but instead they were being skipped on all Node versions >= 10.
=> Only skip certain global-related tests on Node v10

test/web-platform-tests/to-upstream/dom/nodes/HTMLCollection-live-mutations.html, test/web-platform-tests/to-upstream/dom/nodes/NodeList-live-mutations.html
Add tests for live `NodeList` and `HTMLCollection` to ensure that the collections are always in sync when the DOM gets updated.
Fixes #77.
=> Add live collection tests

test/web-platform-tests/run-wpts.js
Currently, each&nbsp;**Node.js**&nbsp;version needs&nbsp;to&nbsp;have its&nbsp;own&nbsp;`needs‑node*`&nbsp;reason added&nbsp;to&nbsp;`run‑wpts.js`.
This&nbsp;is&nbsp;problematic, as&nbsp;the&nbsp;code currently&nbsp;performs the&nbsp;`Number(process.versions.node.split(".")[0])`&nbsp;conversion for&nbsp;every&nbsp;supported&nbsp;`needs‑node*`&nbsp;entry, and&nbsp;each&nbsp;`needs‑node*`&nbsp;entry has&nbsp;to&nbsp;be&nbsp;manually&nbsp;added.
This&nbsp;simplifies&nbsp;that to&nbsp;only&nbsp;need to&nbsp;perform that&nbsp;conversion&nbsp;once.
I’ve&nbsp;also&nbsp;added a&nbsp;fail&nbsp;reason to&nbsp;<code>[expected&nbsp;fail]</code> when&nbsp;the&nbsp;reason is&nbsp;`needs‑node*` or&nbsp;`fail‑with‑canvas`.
=> test(wpt): Improve “expected fail” message and “needs‑node*” code

lib/jsdom/browser/Window.js
Closes #2795.
I manually tested this (using nvm). I'm not sure it's worth testing on CI, but if we wanted to I think something like this (not tested) could work:
```yaml
- node_js: stable
ENV: TEST_SUITE=downlevel
script:
- nvm use 10
- yarn test-api
```
=> Fix Node v10 and Node v11 support

test/web-platform-tests/run-wpts.js, test/web-platform-tests/to-run.yaml
The `mutates-global` failure reason is not needed anymore after the release of the constructor and prototype reform.
=> Remove mutates-globals test failure reason

package.json, test/web-platform-tests/to-upstream/cssom/element-style-color.html, yarn.lock
I pinpointed the issue #2639 to a problem with cssstyle.
I submitted a PR on cssstyle (see https://github.com/jsdom/cssstyle/pull/109) and added a test here.
I can rename/move the test if you feel it is not in the right place.
In order for this test to pass, we need to merge/release a new version of cssstyle, bump the version used by jsdom and rerun the test.
Concerning issue #825, I could not reproduce the issue. It may have been fixed by a cssstyle update since 2014?
=> Add test for issue 2639 - setting rgba color style

.mailmap, AUTHORS.txt, package.json
I'm no longer as concerned about sharing personal details in connection to my online accounts as I once was, so it's about time I made this change 🙂
=> Replace alias with my actual name as contributor/maintainer

lib/jsdom/browser/Window.js, test/api/virtual-console.js, test/web-platform-tests/to-upstream/console/methods.html
Support for `console.timeLog()` was added in Node.js v10.7.0, and this wraps it like our other `console` methods. With this we expose every method from the current Console Standard.
=> Add console.timeLog()

lib/jsdom/browser/parser/html.js
The monkey-patch for maintaining the open element stack, as modified by commit 75a921eab52c239b2468e08be9f547f46c7f86bd, maintained a reference to the most recent `JSDOMParse5Adapter` (and all its options) through the push/pop closures. This means there was always a reference from the rooted `OpenElementStack.prototype.{push,pop}` functions to the most recent `JSDOMParse5Adapter` and its related objects.
This commit instead uses the `this.treeAdapter` pointer, which already exists in parse5. Doing so also allows us to move the monkey-patch back into the top level, instead of establishing it on construction of each tree adapter.
Closes #2831. Closes #2825. Fixes https://github.com/facebook/jest/issues/9507.
---
Hi @lamhieu-vk and @terite; thank you very much for your pull requests to fix …
=> Fix leaking memory during parsing

lib/jsdom/browser/parser/xml.js, package.json, yarn.lock
This PR upgrades saxes to version 5.0.0.
Why upgrade? Other than keeping up with the latest version, there's a BOM bug that is fixed in saxes 5.0.0 which in theory could be triggered in jsdom as long as jsdom remains on 4.x. (The other bug fixes in 5.0.0 fix issues that don't affect jsdom.)
=> Upgrade saxes to version 5.0.0.

lib/jsdom/living/nodes/HTMLSelectElement-impl.js, test/web-platform-tests/to-upstream/html/semantics/forms/the-select-element/select-selectedOptions-and-value.html
Fixes #2908, which happened because changing the `select.value` was not correctly updating the internal `_version` field, which is used to optimise `HTMLCollection`, `HTMLOptionCollection`, `NodeList` and several other things.
=> fix(HTMLSelectElement): Update version in value setter

lib/jsdom/living/nodes/HTMLInputElement-impl.js, test/web-platform-tests/to-upstream/html/semantics/forms/the-input-element/input-step-realignment.html
When the value is not step aligned, align to nearest step multiple in appropriate direction. Only proceed to apply the step delta if the value WAS step aligned, and not otherwise.
Files changed:
lib/jsdom/living/nodes/HTMLInputElement-impl.js
Closes #2826
=> Ensure <input type="number"> doesn't overshoot step up/down values

lib/jsdom/living/events/EventTarget-impl.js, lib/jsdom/living/helpers/form-controls.js, lib/jsdom/living/helpers/number-and-date-inputs.js, lib/jsdom/living/nodes/HTMLLabelElement-impl.js, test/web-platform-tests/to-upstream/html/semantics/forms/the-label-element/clicking-interactive-content.html, test/web-platform-tests/to-upstream/html/semantics/forms/the-label-element/clicking-noninteractive-labelable-content.html, test/web-platform-tests/to-upstream/html/semantics/forms/the-label-element/clicking-noninteractive-unlabelable-content.html
This commit deals with two cases where the current activation behavior for `<label>` elements is deficient:
- When the target of the event that triggered said activation behavior is in fact part of some interactive content descendant of the `<label>`, then nothing should be done.
- When the target of the event is an inclusive descendant of the labeled control, then the control presumably has already received this event, so nothing more should be done by the `<label>` element.
The former case is specifically treated by the spec as a no-op case, under https://html.spec.whatwg.org/C/#the-label-element. This applies to such trees as
```html
<label>
<button>Click me!</button>
</label>
```
Since the `<button>` is labelable, if upon clicking the button the `<label>` element tries to click the …
=> Better activation behavior for <label> elements

test/README.md
It seems like there's a new URL which doesn't redirect from `www.`
=> Fix web-platform-tests documentation link

lib/jsdom/living/nodes/HTMLImageElement-impl.js, test/web-platform-tests/to-upstream/html/semantics/embedded-content/the-img-element/reuse-img.html
HTMLImageElement reuses its internal Canvas.Image object when the <img>'s src attribute is changed. However, the Image#onerror callback is not adjusted to report the error for subsequent loads. This means that a second failing load might cause onload to be called instead of onerror.
Fix this issue by attaching an onerror handler every time we load, not just when we create the Canvas.Image.
=> Fix <img> onerror not called when resetting src

lib/jsdom/living/helpers/focusing.js, lib/jsdom/living/nodes/HTMLOrSVGElement-impl.js, test/web-platform-tests/to-run.yaml, test/web-platform-tests/to-upstream/html/interaction/focus-managment/focusing-focused-noop.html
This PR alters how `HTMLOrSVGElement-impl` so that the `focus` and `blur` methods also dispatch the relevant `focusin` and `focusout` events in the bubble phase, as per how they occur on modern browsers. I wasn't sure where to add any tests for this change specifically, if anyone has any pointers, that would be great.
=> Ensure focusin/focusout fires with .focus()/.blur()

lib/jsdom/living/nodes/Element-impl.js
`ByRole` from `@testing-library/dom` makes heavy use of window.getComputedStyle. This makes Element.prototype.tagName a hotpath in certain DOM trees. Where `asciiUppercase` can take up to 40% of the total time. Since all the conditions checked in `get tagName()` seem invariant we can cache the result and return that instead after the first computation.
For our specific benchmark we saw a drop of the median runtime down to 261.3774ms from 538.9752ms (which corresponds to the 40% of total time of `asciiUppercase`.
Benchmark repo: https://github.com/eps1lon/jsdom-tagName-cache
=> feat: Cache Element.prototype.tagName

lib/jsdom/browser/Window.js, lib/jsdom/living/helpers/style-rules.js, test/web-platform-tests/to-upstream/css/cssom/getComputedStyle-pseudo-shadow.html
Extracted from <https://github.com/jsdom/jsdom/pull/2835>.
This makes [`getComputedStyle(…)`](https://drafts.csswg.org/cssom/#dom-window-getcomputedstyle) call `notImplemented(…)` when trying to use the `pseudoElt` parameter, and throw when trying to get the computed style of a **Shadow DOM** pseudo‑element.
See also <https://github.com/jsdom/jsdom/issues/1928>
- https://drafts.csswg.org/cssom/#dom-window-getcomputedstyle
---
review?(@TimothyGu): The build passed
=> fix(getComputedStyle): throw on Shadow DOM pseudo‑elements

lib/jsdom/browser/Window.js, lib/jsdom/living/custom-elements/CustomElementRegistry-impl.js, lib/jsdom/living/custom-elements/CustomElementRegistry.webidl, lib/jsdom/living/events/CloseEvent.webidl, lib/jsdom/living/events/event-handlers.webidl, lib/jsdom/living/helpers/create-element.js, lib/jsdom/living/helpers/create-event-accessor.js, lib/jsdom/living/helpers/custom-elements.js, lib/jsdom/living/helpers/html-constructor.js, lib/jsdom/living/mutation-observer/MutationObserver.webidl, lib/jsdom/living/nodes/DOMStringMap.webidl, lib/jsdom/living/nodes/Element.webidl, lib/jsdom/living/nodes/HTMLOrSVGElement.webidl, lib/jsdom/living/nodes/HTMLSlotElement.webidl, lib/jsdom/living/nodes/Node.webidl, lib/jsdom/living/nodes/SVGGraphicsElement.webidl, package.json, test/web-platform-tests/to-run.yaml, yarn.lock
---
<details>
<summary><strong>Benchmark results</strong></summary>
| benchmark                                                                                    | `master`                                                                                        | `feat/use‑callback‑functions`
| ---------                                                                                    | --------                                                                                        | --------------------------------------
| dom/compare-document-position/compare&nbsp;ancestor                                          | jsdom  ×&nbsp;31,761&nbsp;ops/sec ±2.80%&nbsp;(10&nbsp;runs&nbsp;sampled)                       | jsdom  ×&nbsp;30,750&nbsp;ops/sec ±5.61%&nbsp;(9&nbsp;runs&nbsp;sampled)
| …
=> Convert JSDOM to use callback functions

lib/jsdom/living/xhr/xhr-utils.js, test/web-platform-tests/to-upstream/xhr/access-control-preflight-request-allow-headers-returns-star.any.js, test/web-platform-tests/to-upstream/xhr/access-control-preflight-request-allow-headers-returns-star.html, test/web-platform-tests/to-upstream/xhr/resources/access-control-preflight-request-allow-headers-returns-star.py
This PR improves on #2867 adding proper formatting. Solves #2408 
The tests fail for this PR on the latest node version [because they're failing on master](https://travis-ci.com/github/silviot/jsdom/builds/199962084).
I would love adding a test for this fix, but it looks like tests come from a different repository, and I'm not familiar at all with this codebase. If needed I can add a test, but I need some pointers about how to do it.
=> fix: support wildcard for access-control-allow-headers

lib/api.js, lib/jsdom/living/helpers/iterable-weak-set.js, lib/jsdom/living/nodes/Document-impl.js, lib/jsdom/living/traversal/NodeIterator-impl.js, lib/jsdom/utils.js
When `WeakRef`s are supported (**Node ≥14.6.0**), then it’s possible to keep track of active `NodeIterator`s without leaking memory.
---
**Refs:** <https://github.com/tc39/proposal-weakrefs/issues/17#issue-292572565>
=> Use `IterableWeakSet` for `NodeIterator` tracking when supported

test/to-port-to-wpts/misc2.js, test/web-platform-tests/to-upstream/jsdom/misc/test_body_event_handler_inline.html
It’s been bothering me that this is the only non‑**WPT** test that is skipped, so I decided to take a crack at fixing it.
---
This still fails in the browser, this time with a `TypeError` stack trace:
```
Error: Uncaught TypeError: Cannot read property '_ownerDocument' of undefined
/tmp/lib/jsdom/living/events/EventTarget-impl.js:340:1 <- /tmp/d02cce143d09f2d44600f80c43efc350.browserify.js:6911
```
The line is in: <https://github.com/jsdom/jsdom/blob/19884d85f9c8f3e7ce2f3ad68c7b86d00674bef8/lib/jsdom/living/events/EventTarget-impl.js#L333-L343>
=> Convert skipped inline event handlers on body test to WPT

test/web-platform-tests/run-wpts.js
The `failCount` calculation was wrong.
---
Extracted from: <https://github.com/jsdom/jsdom/pull/3155>
=> fixup! Handle failing subtests in web‑platform‑tests

lib/jsdom/living/helpers/create-event-accessor.js, test/web-platform-tests/to-upstream/html/webappapis/events/event-handler-object-environment-instantiation.html
This uses a method similar to what’s done by [the **Realms** shim](https://github.com/Agoric/realms-shim/blob/067bdd9404013e95b9603379cb1fb597f0bfdc50/src/evaluators.js#L60-L68).
It also works around the bug that prevents using a `Proxy` for the [named properties object](https://heycam.github.io/webidl/#named-properties-object): <https://github.com/jsdom/webidl2js/pull/167> and prevents a global `element` or `formOwner` variable from breaking the inner `with`s and also ensures that if there isn’t such a variable, it’s not added to the scope due to being passed as a named parameter.
- <https://github.com/whatwg/html/issues/6079>
- <https://github.com/whatwg/html/pull/6086>
=> Fix event handler ObjectEnvironment instantiation

lib/jsdom/living/domparsing/InnerHTML-impl.js, lib/jsdom/living/domparsing/InnerHTML.webidl, lib/jsdom/living/nodes/Element-impl.js, lib/jsdom/living/nodes/Element.webidl, lib/jsdom/living/nodes/ShadowRoot-impl.js, lib/jsdom/living/nodes/ShadowRoot.webidl
<https://github.com/w3c/DOM-Parsing/issues/21> has been resolved, so this can be updated.
I’ve kept the implementations in `Element‑impl.js` and `ShadowRoot‑impl.js`, as they have little actual overlap.
=> Use `InnerHTML` mixin for `innerHTML` definition

test/web-platform-tests/to-run.yaml
Part of: <https://github.com/jsdom/jsdom/issues/3157>
---
I only converted the tests where the failing test count was relatively small.
=> Convert WPTs in `custom‑elements` directory to use the new format

lib/jsdom/living/helpers/mutation-observers.js, test/web-platform-tests/to-upstream/dom/nodes/MutationObserver-callback-tricky.html
The code was misindented relative to the spec.
Fixes #3096. Fixes #3172.
=> Fix MutationObserver infinite loop bugs

README.md
<http://url.spec.whatwg.org/> and <http://groups.google.com/group/jsdom> are being redirected to HTTPS already, but now linking straight to HTTPS :)
=> README.md: Replace two HTTP links with HTTPS

package.json, yarn.lock
move to websockets 7.4.6 to patch out ReDoS vulnerability. closes #3196
=> bump to websockets 7.4.6 to fix ReDoS vulnerability

lib/jsdom/living/websockets/WebSocket-impl.js, package.json, yarn.lock
Previously, it was ignoring the strictSSL option and always sending `rejectUnauthorized: undefined` to the ws module (which eventually sends it to Node.js). The meaning of `rejectUnauthorized: undefined` changed in https://github.com/nodejs/node/commit/6c7fff6f1d (Node.js v16.6.2), which caused this problem to suddenly be visible on CI.
Also updates the ws module since I did that anyway while debugging.
Closes #3243.
(I guess I'll put this bug into the category of issues TypeScript could have saved us from...)
=> Fix SSL certificate checking for WebSockets

lib/jsdom/living/nodes/Element-impl.js, test/web-platform-tests/to-upstream/dom/nodes/Element-tagName.html
Since commit 63d24a0, the tagName is still uppercase even if the element
is inserted in a XML document.
=> Don't uppercase tagName when element is appended to XML document

lib/jsdom/living/nodes/HTMLInputElement-impl.js, test/web-platform-tests/to-upstream/html/semantics/forms/the-input-element/input-valueasdate.html
According to https://html.spec.whatwg.org/multipage/input.html#dom-input-valueasdate
setting valueAsDate to null should lead to setting the inputs' value to an
empty string.
Previously setting a null value led to an error
"Cannot read properties of null (reading 'getUTCFullYear')" due to
actually trying to convert null to a date
https://stackblitz.com/edit/node-pshahn?file=index.js
```js
const jsdom = require('jsdom');
const { JSDOM } = jsdom;
const dom = new JSDOM(`<!DOCTYPE html><input type="date">`);
dom.window.document.querySelector('input').valueAsDate=null
```
=> Fix valueAsDate for HtmlInputElement with null values

lib/jsdom/living/nodes/Node-impl.js
"n" here refers to the tree depth of the node being inserted, so lots of nested elements causes insertion to be extremely slow. Deep cloning, for example, calls `_insert` O(n) times, which makes cloning O(n^3) without this optimization and O(n^2) with it.
**This can make the difference between minutes and milliseconds** of synchronous blocking time for very deep node trees (which is my use case and what led me to need this optimization).
It works by only checking `isConnected` (which is O(n)) once on the node being inserted rather than checking it on every single descendant of the node being inserted. As far as I know, checking `isConnected` for every descendant isn't necessary since any node should have the same `isConnected` value as any other node in the same node tree.
The current …
=> Major performance improvements in some cases

lib/jsdom/browser/parser/html.js, test/api/methods.js
Fixes #2968.
Specifically, this disables location information for nodes created by the HTML parser's `parseFragment`, which is used for `innerHTML`, `outerHTML`, and `createContextualFragment`. It does not change anything for nodes created by `parseIntoDocument`. Note that `nodeLocation` will return `undefined` rather than throwing for these nodes, which matches the behavior prior to https://github.com/jsdom/jsdom/commit/49353e224b6c59e48c3cc7da3700dbe93a2286ac.
In https://github.com/jsdom/jsdom/issues/2968#issuecomment-980497117 I mentioned three other APIs. Those all use `parseIntoDocument` and so are unaffected, but for reference:
- DOMParser's `parseFromString` is [not forwarding along `parseOptions`](https://github.com/jsdom/jsdom/blob/a61fdb886a30fce6a3aa68002e1af6e5bcb4c372/lib/jsdo …
=> Do not track location information for nodes created by innerHTML

test/api/fixtures/timeout-with-gc.js, test/api/from-outside.js
Recent changes to Node.js have made it so that less memory appears to be freed when clearing timers. Let's say that as long as at least 90% of the memory is freed, we don't have the bug this was testing against.
=> Revise timer GC test to be more lenient

lib/jsdom/browser/Window.js, lib/jsdom/living/crypto/Crypto-impl.js, lib/jsdom/living/crypto/Crypto.webidl, lib/jsdom/living/interfaces.js, scripts/webidl/convert.js, test/web-platform-tests/to-run.yaml
This is the only member of `crypto` that is available even in non-secure contexts.
---
Motivation: Since we fixed a security in Scala.js related to `java.util.UUID.randomUUID()` (see https://github.com/scala-js/scala-js/security/advisories/GHSA-j2f9-w8wh-9ww4), the need for `crypto.getRandomValues` has become quite high. `jsdom` is one of the main testing environments used by the Scala.js community. The lack of `getRandomValues` is now causing several maintainers and project authors to use insecure variants because of `jsdom`. This in turn risks exposing them to security vulnerabilities of their own. I hope that by actually providing `crypto.getRandomValues` in `jsdom`, we will avoid this problematic situation.
---
This is my first contribution to `jsdom`. Don't hesitate to tell me if …
=> Implement crypto.getRandomValues(array).

lib/jsdom/living/helpers/selectors.js, test/web-platform-tests/to-upstream/css/cssom/getComputedStyle-root.html
The :root pseudo-selector isn't currently working correctly. For example, if custom properties are defined in :root, they will not be available to the rest of the document or through "getComputedStyle(document.documentElement)."
It looks like this is due to the way nwsapi determines whether something matches the :root selector. It does a equality (===) comparison between the document.documentElement and the element provided to match(). These both need to be the "wrapper" class for the comparison to work correctly. As currently implemented, the "wrapper" is compared to the "implementation".
The proposed change provides the "wrapper" to nwsapi as the document. I've also added another test to verify the change.
=> Fix :root pseudo-selector

lib/jsdom/living/window/History-impl.js, lib/jsdom/living/window/Location-impl.js, test/web-platform-tests/to-upstream/html/browsers/history/the-location-interface/location-getters-about-blank.html
This broke in 6c1f0585e33afceff2e802867f2abaee1c08f48f when we upgraded whatwg-url without adapting Location for its breaking changes.
Some fixes here (e.g. to the setters) are not really testable, since we never navigate after changing the host or port of an opaque-path URL anyway. But we include them for completeness.
Closes #3431.
=> Fix location.pathname getter on opaque-path URLs

benchmark/html/index.js, benchmark/html/select.js, lib/jsdom/living/nodes/HTMLSelectElement-impl.js
Previous implementation of adding 'option' elements to 'select' elements caused an '(N*N/2)' issue where all previous elements would be added to an array to find either the last selected or first non disabled. Now this logic is run on just the 'option' element being appended.    
```
yarn benchmark -suites=html
yarn run v1.22.19
$ node ./benchmark/runner -suites=html
jsdom  x 1.56 ops/sec ±3.61% (8 runs sampled)
Done in 11.29s.
```
```
yarn benchmark -suites=html
yarn run v1.22.19
$ node ./benchmark/runner -suites=html
jsdom  x 10.15 ops/sec ±6.53% (31 runs sampled)
Done in 7.23s.
```
Discovered this when I passed some html with a select with 20k option elements to JDSOM.
First pass at a fix and first time writing anything for nodejs so any and all feedback welcome including this not …
=> Performance of appending option to select

package.json, test/web-platform-tests/to-run.yaml, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-All-scope.html, yarn.lock
Here are the tests reproducing the errors from https://github.com/jsdom/jsdom/issues/3141
Current behavior
---
Simple :scope selectors work as expected.
```
div.querySelector(":scope > p");
div.querySelectorAll(":scope > p"),
```
Comma separated :scope selectors throw an exception.
```
div.querySelector(":scope > p, :scope > div");
div.querySelectorAll(":scope > p, :scope > div");
```
Output
```
Failed in "querySelector comma separted":
unknown pseudo-class selector ':scope>*'
SyntaxError: unknown pseudo-class selector ':scope>*'
at emit (../jsdom/node_modules/nwsapi/src/nwsapi.js:565:17)
at compileSelector (../jsdom/node_modules/nwsapi/src/nwsapi.js:1292:17)
at compile (../jsdom/node_modules/nwsapi/src/nwsapi.js:753:16)
at collect (../jsdom/node_modules/nwsapi/src/nwsapi.js:1553:24)
at …
```
=> Tests for querySelector(All) with comma separated :scope pseudo selector

lib/jsdom/living/xhr/xhr-utils.js, test/web-platform-tests/to-upstream/xhr/abort-with-error.any.js
Thanks @domenic and team for the great project,
Your XMLHttpRequest implementation wraps an internal client called `client`.  When we abort the request it aborts the internal client [here](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/xhr/XMLHttpRequest-impl.js#L364).  Now this internal client is created in `xhr-utils.createClient` which has a number of paths for data url, file url etc.  At the catch statement [here](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/xhr/xhr-utils.js#L326) we still assign client, but it is an `EventEmitter` which lacks an abort method.  If we then try to abort the wrapping XMLHttpRequest it throws a strange exception which doesn't tell the user about the true root cause.  I suggest adding an empty abort method to prevent confusion. …
=> add missing abort method for sad path

lib/jsdom/living/events/EventModifierMixin-impl.js, test/web-platform-tests/to-upstream/uievents/getModifierState.html
This fixes #3126 
Chrome, Firefox, and Edge all return true for `getModifierState('Control')` when the `ctrlKey` property is true. Same for alt, meta, and shift modifiers as well. The spec doesn't seem to mention how the method should determine if a modifier is activated (https://www.w3.org/TR/uievents/#dom-keyboardevent-getmodifierstate) and since the `xKey` properties are the only ones on the instance that carry information about the state of these 4 modifiers, makes sense to look at those props for these 4 modifiers.
=> fix(getModifierState): query the correct property for alt, ctrl, meta, and shift keys

lib/jsdom/browser/Window.js, lib/jsdom/living/helpers/custom-elements.js, lib/jsdom/living/helpers/html-constructor.js, test/web-platform-tests/to-upstream/custom-elements/overwritten-customElements-global.html
jsdom currently finds the global custom elements registry by reading the sandbox-writable `.customElements` property of the global object. This means that code running in the sandbox can break jsdom by overwriting or deleting that property. This PR updates jsdom to store and look up a global object's custom element registry through a `_`-prefixed property instead (similar to `._document`).
=> Don't look up the global custom elements registry through its sandbox-writable property.

.github/workflows/jsdom-ci.yml
This PR:
-   Declares the minimum permissions for CI workflows to run at the workflow level, following principle of least privilege; see [related GitHub security post](https://securitylab.github.com/research/github-actions-building-blocks/)
-   Bumps GitHub Actions to their latest major versions, which now use Node 16 internally instead of Node 12 (EOL as of end of April 2022, no longer receives security updates):
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)
=> Update GitHub Actions

lib/jsdom/living/nodes/HTMLInputElement-impl.js, test/web-platform-tests/to-upstream/html/semantics/forms/form-submission-0/form-submitters.html
See https://html.spec.whatwg.org/multipage/input.html#image-button-state-(type=image)
I added a general input/button form submission test to assert which ones should/ should not submit a form, as I didn't see one in the existing wpt/tuwpt tests.
=> Allow Image Buttons to submit forms

benchmark/html/index.js, benchmark/html/select.js, lib/jsdom/living/nodes/HTMLSelectElement-impl.js, test/web-platform-tests/to-upstream/html/semantics/forms/the-select-element/select-selectedOptions-and-selected.html
Closes https://github.com/jsdom/jsdom/issues/3476
Reverts https://github.com/jsdom/jsdom/pull/3404 which broke `HTMLSelectElement.selectedOptions` when `HTMLOptionElement.selected` is set (revealed by broken `accname/name_file-label-embedded-select-manual.html` in https://github.com/eps1lon/dom-accessibility-api/pull/874
Browser:  HTMLOptionElement.selected
Pre 20.0.1: https://runkit.com/eps1lon/63ad844e952ef10008dda4f7
20.0.1: https://runkit.com/eps1lon/63ad82c22f199e000881c52e
=> Revert "Improve performance of appending <option> to <select>"

lib/jsdom/living/nodes/ElementCSSInlineStyle-impl.js
This is generated by webidl2js from the [PutForwards] annotation in the IDL file.
Closes #3045. Closes #3044.
=> Remove redundant style setter

lib/jsdom/browser/resources/per-document-resource-loader.js, test/web-platform-tests/to-upstream/html/semantics/scripting-1/the-script-element/dynamically-created-defer-script.html, test/web-platform-tests/to-upstream/html/semantics/scripting-1/the-script-element/resources/dynamically-created-defer-script.js
Closes #3451. Closes #3453 by superseding it with tests.
=> Fix defer="" scripts inserted after DOMContentLoaded

lib/jsdom/living/events/MouseEvent-impl.js, lib/jsdom/living/events/MouseEvent.webidl, test/web-platform-tests/to-upstream/html/editing/activation/click-event-properties.html
Ensure that the [CSSOM View MouseEvent attributes](https://www.w3.org/TR/cssom-view/#extensions-to-the-mouseevent-interface) are set. Specifically this ensures that `x`/`y` mirror `clientX`/`clientY` and that `offsetX`/`offsetY` are set (always `0` since there is no layout).
Fixes #3483, #3470
Builds on and supersedes #3472 (reworks it to fix the default case and the tests)
=> Add CSSOM View extensions to MouseEvent

lib/jsdom/browser/Window.js, lib/jsdom/living/helpers/style-rules.js, test/web-platform-tests/to-upstream/cssom/getComputedStyle-visibility-unset.html
Add support for the CSS-wide `unset` keyword when computing styles in `getComputedStyle()`. An `unset` value removes any previously set values for the element and forces it to be inherited or have initial value.
A companion PR to #3478, they should probably get merged together. The inspiration for this PR was seeing `unset` being handled in `@testing-library/user-event`'s [`closestPointerEventsDeclaration` helper](https://github.com/testing-library/user-event/blob/1aa2027e5ec445ab413808556efa7763b65053d3/src/utils/pointer/cssPointerEvents.ts#L22-L32).
=> Add support for unset CSS keyword to getComputedStyle()

lib/jsdom/browser/Window.js, lib/jsdom/living/helpers/style-rules.js, lib/jsdom/living/helpers/stylesheets.js, lib/jsdom/living/nodes/Document-impl.js, lib/jsdom/living/nodes/HTMLLinkElement-impl.js, lib/jsdom/living/nodes/Node-impl.js, test/web-platform-tests/to-upstream/cssom/getComputedStyle-mutations.html, test/web-platform-tests/to-upstream/cssom/getComputedStyle-style-element-updates.html, test/web-platform-tests/to-upstream/html/semantics/document-metadata/the-link-element/stylesheet-appropriate-time-to-obtain.html
Fixes #3234. Caches the computed styles for each element, avoiding expensive re-calculations. Also, modifies the implementation of `getResolvedValue` to not match all the style rules for itself, but reuse the cached results.
Each document has its own cache, and the cache is completely invalidated on every DOM change. I looked up all `queueMutationRecord` calls and added an `invalidateStyleCache` call to every place that also triggers a mutation observer.
What are the actual performance improvements? I tested it on one of our React Testing Library unit test suites in the [Gutenberg](https://github.com/wordpress/gutenberg) project. Before the patch, the suite takes 11.0 s to run:
```
PASS  packages/components/src/border-box-control/test/index.js (10.066 s)
BorderBoxControl
Linked view …
```
=> Cache element styles for getComputedStyle

lib/jsdom/living/helpers/style-rules.js, test/web-platform-tests/to-upstream/cssom/getComputedStyle-pointerEvents.html
This PR is adding support for inheritance of the `pointer-events` CSS property to `getComputedStyle()`. If a parent element specifies `pointer-events: none`, then for a child element `getComputedStyle(childEl).pointerEvents` should be `none`, too.
This has been implemented for `visibility` for some time, and `pointer-events` is also an "Inherited: yes" ([#](https://svgwg.org/svg2-draft/interact.html#PointerEventsProperty)) property, with the same inheritance behavior, and deserves to be supported.
A real-world impact of this should be improved performance of Testing Library, namely the [`closestPointerEventsDeclaration` helper](https://github.com/testing-library/user-event/blob/1aa2027e5ec445ab413808556efa7763b65053d3/src/utils/pointer/cssPointerEvents.ts#L22-L32) in …
=> Add inheritance for pointer-events to getComputedStyle()

lib/api.js, test/api/methods.js
Previously, after using JSDOM.reconfigure() to change the URL, the History API held onto a cached version of the previous URL. This means if one used the History API like:
window.history.replaceState(null, "");
The cached URL would be used to replace the value of window.location.href back to the original. This is unexpected. Not supplying a third argument should not change the URL.
To fix, update the current history entry when calling reconfigure().
Fixes #3504
=> Make JSDOM.reconfigure() adjust the History API with the updated URL

lib/jsdom/living/window/Location-impl.js, test/web-platform-tests/to-upstream/html/browsers/history/the-location-interface/location-hash-setter-empty-string.html
Closes #3494. Closes #3495 by superseding it.
=> Fix location.hash setter with the empty string input

lib/jsdom/living/crypto/Crypto-impl.js, lib/jsdom/living/crypto/Crypto.webidl, test/web-platform-tests/to-run.yaml
This implements `crypto.randomUUID()` so that it's available in jsdom environments.
This is my first contribution to jsdom, so let me know if I should be doing anything differently here. I mostly followed #3352 as an example.
=> Implement crypto.randomUUID()

lib/jsdom/living/nodes/HTMLFormElement-impl.js, lib/jsdom/living/nodes/HTMLInputElement-impl.js, lib/jsdom/living/xhr/FormData-impl.js, lib/jsdom/living/xhr/FormData.webidl, test/web-platform-tests/to-run.yaml, test/web-platform-tests/to-upstream/xhr/formdata/constructor-submitter.html
Add support for the new optional `submitter` parameter to the `FormData` constructor. This feature is [implemented in the latest versions](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData#browser_compatibility) of Chrome/Firefox/Safari.
Spec: https://xhr.spec.whatwg.org/#interface-formdata
Spec PR: https://github.com/whatwg/xhr/pull/366
In order to fully implement it in jsdom, this requires more robust Image Button support (i.e. track selected coordinate, use when constructing form data set).
Testing notes:
* The newly enabled WPTs all pass in jsdom and in the big three browsers.
* The newly added to-upstream test passes in jsdom and Chrome/Safari (it fails in Firefox, but that's a Firefox bug imo, I'm planning to file a FF bug and upstream the test out of band)
=> FormData.constructor: implement optional submitter parameter 

lib/jsdom/living/aborting/AbortSignal-impl.js, lib/jsdom/living/aborting/AbortSignal.webidl, test/web-platform-tests/to-run.yaml
Namely, AbortSignal.timeout() and abortSignal.throwIfAborted(). Closes #3516.
=> Implement some AbortSignal methods

lib/jsdom/living/custom-elements/CustomElementRegistry-impl.js
`Array.from` has optional second argument. Calling `map` is not required for this case.
=> Simplified Array.from in convertToSequenceDOMString

lib/jsdom/living/nodes/HTMLInputElement-impl.js, test/web-platform-tests/to-upstream/html/semantics/forms/the-input-element/input-valueasnumber.html
[Relevant part of the Spec](https://html.spec.whatwg.org/multipage/input.html#dom-input-valueasnumber)
NaN is neither finite nor infinite, and requires special handling per the spec, rather than being thrown out with the infinite values at the beginning of the setter.
=> fix: Handle NaN correctly in Input.valueAsNumber setter

lib/jsdom/living/custom-elements/CustomElementRegistry-impl.js, lib/jsdom/living/custom-elements/ElementInternals-impl.js, lib/jsdom/living/custom-elements/ElementInternals.webidl, lib/jsdom/living/helpers/custom-elements.js, lib/jsdom/living/interfaces.js, lib/jsdom/living/nodes/Element-impl.js, lib/jsdom/living/nodes/HTMLElement-impl.js, lib/jsdom/living/nodes/HTMLElement.webidl, lib/jsdom/living/nodes/ShadowRoot-impl.js, test/web-platform-tests/to-run.yaml
It only supports the shadowRoot property for now.
This extracts the basic infrastructure from #3561, leaving the ARIAMixin work for later (to be reconciled with #3586).
=> Implement basic ElementInternals

lib/jsdom/living/nodes/HTMLInputElement-impl.js, lib/jsdom/living/nodes/HTMLInputElement.webidl, lib/jsdom/living/nodes/HTMLTextAreaElement.webidl, scripts/webidl/convert.js, test/web-platform-tests/to-run.yaml
This makes maxLength and minLength have the precisely correct semantics for HTMLInputElement and HTMLTextAreaElement. And the code is now fully generated, instead of hand-coded.
=> Implement full long reflection

lib/jsdom/browser/Window.js
The error message previously mentioned `window.computedStyle` which does not exist. Instead it should say `window.getComputedStyle`.
=> Fix `window.getComputedStyle` error message

Contributing.md
- These URLs now link directly to the moved location
=> Update URLs that have been moved

lib/jsdom/living/fetch/Headers-impl.js, lib/jsdom/living/fetch/Headers.webidl, lib/jsdom/living/fetch/header-list.js, test/web-platform-tests/to-run.yaml
I've implemented the `getSetCookie` method of `Headers`. The `HeaderList` data structure has been changed accordingly.
See here for the specification of the `getSetCookie` method.
https://developer.mozilla.org/en-US/docs/Web/API/Headers/getSetCookie
With this fix, the `header-setcookie.any.html` test is resolved except for a failure due to `Response` not being implemented.
before
```
1) web-platform-tests
fetch/api/headers
header-setcookie.any.html:
18/24 errors in test:
Failed in "Headers iterator does not combine set-cookie headers":
assert_equals: Array length is not equal expected 2 but got 1
...
```
after
```
1) web-platform-tests
fetch/api/headers
header-setcookie.any.html:
1/24 errors in test:
Failed in "Set-Cookie is a forbidden response header"
Response is not defined
```
=> Implement the getSetCookie method of Headers

lib/jsdom/living/nodes/HTMLOrSVGElement-impl.js, lib/jsdom/living/selection/Selection-impl.js, test/web-platform-tests/to-upstream/selection/document-selectionchange.html
I want to test my contenteditable component that relies on `selectionchange` events. When debugging why my tests doesn't reflect browser behaviour, I found this TODO:
https://github.com/jsdom/jsdom/blob/main/lib/jsdom/living/selection/Selection-impl.js#L335
This PR addresses that TODO by triggering `selectionchange` event on `document` as stated in the spec. I added missing tests as well.
=> Trigger selectionchange event on document when selection changes (small change - 2 files)

lib/jsdom/browser/Window.js, test/web-platform-tests/to-run.yaml
Restructure Window.js to be less convoluted, with a single createWindow function and no fake Window constructor that operates on a this object but then manually sets is prototype chain anyway.
=> Refactor Window object setup code

lib/jsdom/browser/Window.js, test/web-platform-tests/to-run.yaml
Previously it was set to the Node.js outer realm's Object.prototype.
=> Set EventTarget.prototype to the jsdom's Object.prototype

.github/workflows/jsdom-ci.yml, package-lock.json, package.json
Canvas v3.0.0 is now out of Release Candidate.
~Should canvas v2.x.x compatibility be removed now that a stable version is available for newer node versions?~ (removed)
=> Update optional peer dependency canvas to v3

lib/jsdom/living/aborting/AbortSignal-impl.js, lib/jsdom/living/aborting/AbortSignal.webidl, test/web-platform-tests/to-run.yaml
This PR adds the [AbortSignal.any() static method](https://developer.mozilla.org/docs/Web/API/AbortSignal/any_static) as a line-by-line translation of [the spec](https://dom.spec.whatwg.org/#create-a-dependent-abort-signal).
Thanks to [ezzatron](https://github.com/ezzatron) and [this closed PR](https://github.com/jsdom/jsdom/pull/3738) for paving the way.
=> Add support for static AbortSignal.any method

lib/jsdom/living/nodes/HTMLFrameElement-impl.js, lib/jsdom/living/nodes/ParentNode-impl.js
This is an internal refactoring to improve consistency. In general, we prefer to only deal with impls inside the impl classes. ParentNode's querySelectorAll implementation was not following that rule, creating NodeList wrappers instead of impls.
FYI @hesxenon
=> Make querySelectorAll follow the always-impl rule

README.md
As of this commit, jsdom's package.json refers to canvas 3.x. I've modified this part of the readme to mention 3.x. I also removed mention of 2.x and 1.x, but I don't know if that is a desirable change. I wouldn't know what to replace it with anyway.
If a different modification is preferred, consider this PR as a reminder to change the docs; feel free to rewrite my PR.
=> Update README to say canvas 3.x, not 2.x

package.json
[Node 21.1.0 added a flag to detect module types](https://github.com/nodejs/node/releases/tag/v21.1.0) that became enabled by [default in Node 22.7.0](https://nodejs.org/api/packages.html#syntax-detection).
Declaring the type will cause Node to skip detection on startup, reducing startup time.
Declaring the package type is also considered good practice according to https://nodejs.org/api/modules.html#enabling.
=> Explicitly declare js module type

scripts/webidl/convert.js
This accounts for a chunk of time in running large tests, because asserts always look at HTMLScriptElement's src.
Part of #3154.
=> Add a cache for all [ReflectURL] IDL attributes

test/web-platform-tests/run-tuwpts.js, test/web-platform-tests/to-upstream/html/semantics/forms/form-submission-0/form-submitters.html, test/web-platform-tests/to-upstream/html/webappapis/animation-frames/nested-raf-not-sync.html, test/web-platform-tests/to-upstream/lint.ignore, test/web-platform-tests/to-upstream/selection/document-selectionchange.html, test/web-platform-tests/utils.js
=> Run WPT lint on to-upstream WPTs

test/web-platform-tests/to-upstream-expectations.yaml, test/web-platform-tests/to-upstream/dom/nodes/Element-closest-null-selectors.html, test/web-platform-tests/to-upstream/dom/nodes/Element-matches-active-pseudo-class.html, test/web-platform-tests/to-upstream/dom/nodes/Element-matches-complex-nth-last-of-type.html, test/web-platform-tests/to-upstream/dom/nodes/Element-matches-disabled-pseudo-class.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-All-comma-selector.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-All-scope.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-basic-has.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-case-insensitive.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-host-pseudo-class.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-hyphen-prefix.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-is-nested-pseudo-class.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-multiple-attributes-xml.xhtml, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-nested-nth-child.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-nth-of-type-complex.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-parent-context.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelector-scope-numeric-id.xhtml, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelectorAll-case-insensitive-attribute-flag.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelectorAll-nested-not-has.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelectorAll-not-descendant.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelectorAll-scope-colon-class.html, test/web-platform-tests/to-upstream/dom/nodes/ParentNode-querySelectorAll-scope-colon-id-class.html
These are all drawn from the issue tracker.
=> Add various selectors tests

lib/jsdom/living/xhr/XMLHttpRequest-impl.js, lib/jsdom/living/xhr/multipart-form-data.js, lib/jsdom/living/xhr/xhr-utils.js, package-lock.json, package.json
This allows us to remove the form-data dependency, which was not very efficient, probably not very spec-compliant, and has recently been taken over by a maintainer that bloats it with dependencies.
Closes #3320.
=> Implement our own multipart/form-data serialization

lib/jsdom/living/custom-elements/ElementInternals-impl.js, test/web-platform-tests/to-upstream-expectations.yaml, test/web-platform-tests/to-upstream/custom-elements/ElementInternals-accessibility.html
The web platform test coverage for these was woefully incomplete, so when we added them in d6c0ab258a84a0ce01ee1d0ae78195ddeadaa3aa they did not actually work at all.
Closes #3732.
=> Fix ElementInternals accessibility getters/setters

lib/api.js, scripts/webidl/reflection.js, test/api/methods.js
Closes #3915. This regressed in e88c8aa824407e27088ef275a9e0cb8755348042 and b722cbdd9b72b5a100ffe58b8258e6db9993eb70.
=> Fix reconfigure() not updating base URL caches

lib/jsdom/living/custom-elements/CustomElementRegistry-impl.js, lib/jsdom/living/custom-elements/CustomElementRegistry.webidl, test/web-platform-tests/to-run.yaml
=> Add `customElements.getName()`

test/web-platform-tests/to-upstream-expectations.yaml, test/web-platform-tests/to-upstream/css/cssom/style-flex-shorthand.html
As discussed in https://github.com/jsdom/cssstyle/pull/245, adds a regression test for CSS `flex` shorthand in cssstyle
=> Add cssstyle regression tests for CSS flex shorthand
